#Makefile.dep -- a file to be included by a Makefile
#to compile a Fortran 9x program or library
OBJS = \
L2Interface.o    MLSL3.o  	  PCFModule.o  \
L3CF.o  	 OpenInit.o  	  global_data.o  \
L3DMData.o  	 OutputClose.o    init_tables_module.o  \
 
# using f90makedep.pl to calculate dependencies 
global_data.o: global_data.f90 $(dir1)MLSCommon.o
init_tables_module.o: init_tables_module.f90 $(dir1)intrinsic.o \
	$(dir1)symbol_table.o $(dir1)symbol_types.o $(dir1)tree.o \
	$(dir1)tree_types.o
L2Interface.o: L2Interface.f90 $(dir1)Hdf.o $(dir1)L2GPData.o \
	$(dir1)MLSCommon.o $(dir1)MLSMessageModule.o $(dir1)MLSPCF.o \
	$(dir1)MLSStrings.o $(dir1)SDPToolkit.o L3DMData.o OpenInit.o
L3CF.o: L3CF.f90 $(dir1)MLSCF.o $(dir1)MLSCommon.o $(dir1)MLSMessageModule.o \
	$(dir1)MLSPCF.o $(dir1)MLSStrings.o $(dir1)SDPToolkit.o L3DMData.o \
	PCFModule.o
L3DMData.o: L3DMData.f90 $(dir1)Hdf.o $(dir1)L2GPData.o $(dir1)MLSCommon.o \
	$(dir1)MLSMessageModule.o $(dir1)MLSPCF.o $(dir1)SDPToolkit.o
MLSL3.o: MLSL3.f90 $(dir1)L2GPData.o $(dir1)MLSCF.o $(dir1)MLSMessageModule.o \
	L2Interface.o L3CF.o L3DMData.o OpenInit.o OutputClose.o
OpenInit.o: OpenInit.f90 $(dir1)MLSCF.o $(dir1)MLSCommon.o \
	$(dir1)MLSMessageModule.o $(dir1)MLSPCF.o $(dir1)SDPToolkit.o \
	$(dir1)dates_module.o $(dir2)getCF_m.o L3CF.o L3DMData.o
OutputClose.o: OutputClose.f90 $(dir1)MLSCF.o $(dir1)MLSCommon.o \
	$(dir1)MLSMessageModule.o $(dir1)MLSPCF.o $(dir1)MLSStrings.o \
	$(dir1)SDPToolkit.o L3CF.o L3DMData.o OpenInit.o PCFModule.o
PCFModule.o: PCFModule.f90 $(dir1)MLSCommon.o $(dir1)MLSMessageModule.o \
	$(dir1)MLSPCF.o
 
#End of Makefile.dep
 
