#Makefile.dep -- a file to be included by a Makefile
#to compile a Fortran 9x program or library
OBJS = \
abs_cs_air_cont_m.o  	     daitken_module.o          i_k_star_no_conv_m.o  \
abs_cs_h2o_213g_cont_m.o     dash_to_us.o  	       int_etah_dh_m.o  \
abs_cs_liq_h2o_m.o  	     dcspline_der_m.o          l2pc_file.o  \
abs_cs_o2_cont_m.o  	     do_t_script_m.o  	       l2pc_file_mngmt_sw_m.o  \
aitken_int_m.o  	     dsimpson_module.o         l2pc_file_parameters.o  \
atmos_basis_m.o  	     dump_k_records_m.o        l2pc_file_structures.o  \
c_qsort.o  		     earth_intersection_m.o    l2pc_pfa_structures.o  \
c_qsort2.o  		     edit_line.o  	       l2pcdim.o  \
c_reverse.o  		     ellipse.o  	       mdbeta.o  \
c_search.o  		     ellipse_sw_m.o  	       pfa_beta_intrp_m.o  \
ch_run_setup_m.o  	     eos_mdb.o  	       pfa_db_delta_m.o  \
complete_i_k_m.o  	     ermsg_m.o  	       pfa_dbeta_intrp_m.o  \
create_beta_coeff_m.o        errmsg.o  		       pfa_fwd_model_m.o  \
create_pfa_beta_coeff_m.o    filter_sw_m.o  	       pfa_prep_m.o  \
cs_intrp_m.o  		     format_key_m.o  	       physics.o  \
d_brkline_m.o  		     fov_convolve_m.o          read_uif_m.o  \
d_csinterp_m.o  	     fwd_mdl_m.o  	       refraction_m.o  \
d_cspline_m.o  		     fwd_mdl_set_up_m.o        scrt_dn_m.o  \
d_delta_dt_m.o  	     gauss_legendre_m.o        slabs.o  \
d_exp_cspline_m.o  	     geo_grids_m.o  	       spectro_derivative_m.o  \
d_exp_lintrp_m.o  	     get_angles_m.o  	       strings.o  \
d_get_one_eta_m.o  	     get_atmos_m.o  	       temperature_deriv_m.o  \
d_hunt_m.o  		     get_cs_m.o  	       time_mod.o  \
d_lintrp_m.o  		     get_delta_m.o  	       trapez_int_m.o  \
d_pcspl_m.o  		     get_drad_m.o  	       two_d_polate.o  \
d_polint_der_m.o  	     get_eta_m.o  	       velcor_m.o  \
d_polint_m.o  		     get_pfa_delta_m.o         vert_to_path_m.o  \
d_q_log_m.o  		     get_rad_m.o  	       write_k_records_m.o  \
d_qsort2_m.o  		     gh06.o  		       write_one_record_m.o  \
d_qsort_m.o  		     gl6p.o  		       write_x_i_records_m.o  \
d_solve_quad_m.o  	     hydrostatic_intrp.o       zatmos_deriv_m.o  \
d_stat_temp_m.o  	     i_and_k_star_m.o          zopacity_m.o  \
d_t_script_dtnp_m.o  	     i_hunt_m.o  \
 
# using f90makedep.pl to calculate dependencies 
aitken_int_m.o: aitken_int_m.f90 $(dir1)MLSCommon.o d_cspline_m.o \
	daitken_module.o dsimpson_module.o
atmos_basis_m.o: atmos_basis_m.f90 $(dir1)MLSCommon.o d_lintrp_m.o \
	get_atmos_m.o l2pc_file_parameters.o l2pc_pfa_structures.o l2pcdim.o
ch_run_setup_m.o: ch_run_setup_m.f90 $(dir1)MLSCommon.o d_hunt_m.o
complete_i_k_m.o: complete_i_k_m.f90 l2pc_file_parameters.o \
	l2pc_pfa_structures.o l2pcdim.o
create_beta_coeff_m.o: create_beta_coeff_m.f90 $(dir1)MLSCommon.o \
	abs_cs_air_cont_m.o abs_cs_h2o_213g_cont_m.o abs_cs_liq_h2o_m.o \
	d_hunt_m.o eos_mdb.o l2pc_pfa_structures.o slabs.o
create_pfa_beta_coeff_m.o: create_pfa_beta_coeff_m.f90 $(dir1)MLSCommon.o \
	create_beta_coeff_m.o eos_mdb.o gl6p.o l2pc_pfa_structures.o \
	l2pcdim.o
cs_intrp_m.o: cs_intrp_m.f90 $(dir1)MLSCommon.o d_hunt_m.o eos_mdb.o \
	l2pcdim.o mdbeta.o
daitken_module.o: daitken_module.f90 aitken.f9h
d_brkline_m.o: d_brkline_m.f90 brkline.f9h
d_csinterp_m.o: d_csinterp_m.f90 $(dir1)MLSCommon.o csinterp.f9h
dcspline_der_m.o: dcspline_der_m.f90 d_hunt_m.o d_pcspl_m.o cspline_der.f9h
d_cspline_m.o: d_cspline_m.f90 d_hunt_m.o d_pcspl_m.o cspline.f9h
d_delta_dt_m.o: d_delta_dt_m.f90 $(dir1)MLSCommon.o cs_intrp_m.o \
	d_get_one_eta_m.o ellipse.o gl6p.o two_d_polate.o
d_exp_cspline_m.o: d_exp_cspline_m.f90 d_cspline_m.o exp_cspline.f9h
d_exp_lintrp_m.o: d_exp_lintrp_m.f90 exp_lintrp.f9h
d_get_one_eta_m.o: d_get_one_eta_m.f90 $(dir1)MLSCommon.o get_one_eta.f9h
d_hunt_m.o: d_hunt_m.f90 $(dir1)MLSCommon.o hunt.f9h
d_lintrp_m.o: d_lintrp_m.f90 d_hunt_m.o lintrp.f9h
do_t_script_m.o: do_t_script_m.f90 $(dir1)MLSCommon.o d_stat_temp_m.o \
	l2pcdim.o
d_pcspl_m.o: d_pcspl_m.f90 pcspl.f9h
d_polint_der_m.o: d_polint_der_m.f90 d_hunt_m.o
d_polint_m.o: d_polint_m.f90 d_hunt_m.o polint.f9h
d_qsort2_m.o: d_qsort2_m.f90 qsort2.f9h
d_qsort_m.o: d_qsort_m.f90 qsort.f9h
dsimpson_module.o: dsimpson_module.f90 $(dir1)MLSCommon.o d_cspline_m.o \
	simpson.f9h
d_solve_quad_m.o: d_solve_quad_m.f90 solve_quad.f9h
d_stat_temp_m.o: d_stat_temp_m.f90 $(dir1)MLSCommon.o physics.o stat_temp.f9h
d_t_script_dtnp_m.o: d_t_script_dtnp_m.f90 $(dir1)MLSCommon.o \
	d_get_one_eta_m.o d_stat_temp_m.o l2pcdim.o physics.o
dump_k_records_m.o: dump_k_records_m.f90 $(dir1)MLSCommon.o format_key_m.o \
	l2pc_file_parameters.o l2pc_file_structures.o l2pcdim.o strings.o
earth_intersection_m.o: earth_intersection_m.f90 $(dir1)MLSCommon.o ellipse.o
ellipse.o: ellipse.f90 $(dir1)MLSCommon.o
ellipse_sw_m.o: ellipse_sw_m.f90 $(dir1)MLSCommon.o ellipse.o
eos_mdb.o: eos_mdb.f90 $(dir1)MLSCommon.o
errmsg.o: errmsg.f90 strings.o
filter_sw_m.o: filter_sw_m.f90 $(dir1)MLSCommon.o $(dir1)units.o strings.o
format_key_m.o: format_key_m.f90 $(dir1)MLSCommon.o strings.o
fov_convolve_m.o: fov_convolve_m.f90 $(dir1)MLSCommon.o $(dir1)units.o \
	d_cspline_m.o l2pcdim.o
fwd_mdl_m.o: fwd_mdl_m.f90 $(dir1)MLSCommon.o complete_i_k_m.o d_lintrp_m.o \
	d_t_script_dtnp_m.o do_t_script_m.o dump_k_records_m.o \
	earth_intersection_m.o ellipse.o eos_mdb.o get_delta_m.o get_eta_m.o \
	gl6p.o i_and_k_star_m.o i_k_star_no_conv_m.o l2pc_file_parameters.o \
	l2pc_file_structures.o l2pc_pfa_structures.o l2pcdim.o mdbeta.o \
	pfa_fwd_model_m.o scrt_dn_m.o temperature_deriv_m.o \
	write_k_records_m.o write_x_i_records_m.o zatmos_deriv_m.o \
	zopacity_m.o
fwd_mdl_set_up_m.o: fwd_mdl_set_up_m.f90 $(dir1)MLSCommon.o atmos_basis_m.o \
	ellipse.o eos_mdb.o geo_grids_m.o get_cs_m.o l2pc_file_parameters.o \
	l2pc_file_structures.o l2pc_pfa_structures.o l2pcdim.o mdbeta.o \
	pfa_prep_m.o refraction_m.o
gauss_legendre_m.o: gauss_legendre_m.f90 $(dir1)MLSCommon.o
geo_grids_m.o: geo_grids_m.f90 $(dir1)MLSCommon.o $(dir1)units.o \
	ch_run_setup_m.o d_get_one_eta_m.o d_hunt_m.o d_lintrp_m.o \
	get_atmos_m.o gl6p.o hydrostatic_intrp.o l2pc_file_parameters.o \
	l2pc_pfa_structures.o l2pcdim.o mdbeta.o strings.o vert_to_path_m.o
get_angles_m.o: get_angles_m.f90 $(dir1)MLSCommon.o d_hunt_m.o
get_atmos_m.o: get_atmos_m.f90 $(dir1)MLSCommon.o $(dir1)units.o l2pcdim.o \
	strings.o
get_cs_m.o: get_cs_m.f90 $(dir1)MLSCommon.o eos_mdb.o i_hunt_m.o l2pcdim.o \
	mdbeta.o
get_delta_m.o: get_delta_m.f90 $(dir1)MLSCommon.o cs_intrp_m.o \
	d_get_one_eta_m.o ellipse.o gl6p.o
get_drad_m.o: get_drad_m.f90 $(dir1)MLSCommon.o
get_eta_m.o: get_eta_m.f90 $(dir1)MLSCommon.o
get_pfa_delta_m.o: get_pfa_delta_m.f90 $(dir1)MLSCommon.o d_get_one_eta_m.o \
	ellipse.o gl6p.o pfa_beta_intrp_m.o
get_rad_m.o: get_rad_m.f90 $(dir1)MLSCommon.o d_lintrp_m.o d_qsort_m.o \
	trapez_int_m.o
gh06.o: gh06.f90 $(dir1)MLSCommon.o
gl6p.o: gl6p.f90 $(dir1)MLSCommon.o
hydrostatic_intrp.o: hydrostatic_intrp.f90 $(dir1)MLSCommon.o d_hunt_m.o \
	d_solve_quad_m.o
i_and_k_star_m.o: i_and_k_star_m.f90 $(dir1)MLSCommon.o d_csinterp_m.o \
	d_cspline_m.o d_lintrp_m.o dcspline_der_m.o fov_convolve_m.o \
	hydrostatic_intrp.o l2pc_file_parameters.o l2pc_file_structures.o \
	l2pc_pfa_structures.o l2pcdim.o
i_hunt_m.o: i_hunt_m.f90 $(dir1)MLSCommon.o
i_k_star_no_conv_m.o: i_k_star_no_conv_m.f90 $(dir1)MLSCommon.o \
	d_csinterp_m.o d_cspline_m.o d_lintrp_m.o dcspline_der_m.o \
	hydrostatic_intrp.o l2pc_file_parameters.o l2pc_file_structures.o \
	l2pc_pfa_structures.o l2pcdim.o
int_etah_dh_m.o: int_etah_dh_m.f90 $(dir1)MLSCommon.o
l2pcdim.o: l2pcdim.f90 $(dir1)MLSCommon.o
l2pc_file.o: l2pc_file.f90 $(dir1)MLSCommon.o $(dir1)units.o d_hunt_m.o \
	eos_mdb.o fwd_mdl_m.o fwd_mdl_set_up_m.o get_angles_m.o gl6p.o \
	l2pc_file_mngmt_sw_m.o l2pc_file_parameters.o l2pc_file_structures.o \
	l2pc_pfa_structures.o l2pcdim.o mdbeta.o read_uif_m.o refraction_m.o \
	strings.o time_mod.o velcor_m.o
l2pc_file_mngmt_sw_m.o: l2pc_file_mngmt_sw_m.f90 $(dir1)MLSCommon.o \
	l2pc_file_parameters.o l2pc_file_structures.o l2pcdim.o strings.o \
	time_mod.o
l2pc_file_parameters.o: l2pc_file_parameters.f90 $(dir1)MLSCommon.o l2pcdim.o
l2pc_file_structures.o: l2pc_file_structures.f90 $(dir1)MLSCommon.o \
	l2pc_file_parameters.o
l2pc_pfa_structures.o: l2pc_pfa_structures.f90 $(dir1)MLSCommon.o \
	l2pc_file_parameters.o l2pcdim.o
mdbeta.o: mdbeta.f90 $(dir1)MLSCommon.o
pfa_beta_intrp_m.o: pfa_beta_intrp_m.f90 $(dir1)MLSCommon.o d_hunt_m.o
pfa_db_delta_m.o: pfa_db_delta_m.f90 $(dir1)MLSCommon.o d_get_one_eta_m.o \
	ellipse.o gl6p.o pfa_dbeta_intrp_m.o two_d_polate.o
pfa_dbeta_intrp_m.o: pfa_dbeta_intrp_m.f90 $(dir1)MLSCommon.o d_hunt_m.o
pfa_fwd_model_m.o: pfa_fwd_model_m.f90 $(dir1)MLSCommon.o aitken_int_m.o \
	create_beta_coeff_m.o create_pfa_beta_coeff_m.o d_hunt_m.o \
	d_lintrp_m.o dcspline_der_m.o do_t_script_m.o earth_intersection_m.o \
	ellipse.o eos_mdb.o fov_convolve_m.o get_pfa_delta_m.o gl6p.o \
	hydrostatic_intrp.o l2pc_file_parameters.o l2pc_file_structures.o \
	l2pc_pfa_structures.o l2pcdim.o scrt_dn_m.o spectro_derivative_m.o \
	strings.o zopacity_m.o
pfa_prep_m.o: pfa_prep_m.f90 $(dir1)MLSCommon.o dsimpson_module.o eos_mdb.o \
	filter_sw_m.o l2pc_pfa_structures.o l2pcdim.o strings.o
physics.o: physics.f90 $(dir1)MLSCommon.o
read_uif_m.o: read_uif_m.f90 $(dir1)MLSCommon.o d_brkline_m.o \
	l2pc_file_parameters.o l2pc_file_structures.o l2pc_pfa_structures.o \
	l2pcdim.o strings.o
refraction_m.o: refraction_m.f90 $(dir1)MLSCommon.o d_lintrp_m.o \
	d_solve_quad_m.o l2pcdim.o
scrt_dn_m.o: scrt_dn_m.f90 $(dir1)MLSCommon.o
slabs.o: slabs.f90 $(dir1)MLSCommon.o gh06.o
spectro_derivative_m.o: spectro_derivative_m.f90 $(dir1)MLSCommon.o \
	get_drad_m.o l2pc_pfa_structures.o l2pcdim.o pfa_db_delta_m.o
temperature_deriv_m.o: temperature_deriv_m.f90 $(dir1)MLSCommon.o \
	d_delta_dt_m.o get_drad_m.o l2pc_file_parameters.o \
	l2pc_pfa_structures.o l2pcdim.o
trapez_int_m.o: trapez_int_m.f90 $(dir1)MLSCommon.o
two_d_polate.o: two_d_polate.f90 $(dir1)MLSCommon.o d_get_one_eta_m.o
velcor_m.o: velcor_m.f90 $(dir1)MLSCommon.o $(dir1)units.o strings.o
vert_to_path_m.o: vert_to_path_m.f90 $(dir1)MLSCommon.o d_get_one_eta_m.o \
	d_lintrp_m.o earth_intersection_m.o ellipse.o ellipse_sw_m.o \
	i_hunt_m.o l2pcdim.o
write_k_records_m.o: write_k_records_m.f90 $(dir1)MLSCommon.o \
	l2pc_file_structures.o write_one_record_m.o
write_one_record_m.o: write_one_record_m.f90 $(dir1)MLSCommon.o \
	format_key_m.o l2pc_file_parameters.o l2pc_file_structures.o
write_x_i_records_m.o: write_x_i_records_m.f90 $(dir1)MLSCommon.o \
	l2pc_file_parameters.o l2pc_file_structures.o l2pc_pfa_structures.o \
	l2pcdim.o write_one_record_m.o
zatmos_deriv_m.o: zatmos_deriv_m.f90 $(dir1)MLSCommon.o get_drad_m.o \
	l2pc_file_parameters.o l2pc_pfa_structures.o l2pcdim.o
zopacity_m.o: zopacity_m.f90 $(dir1)MLSCommon.o
 
#End of Makefile.dep
 
