# $Id$
#
# This is an include file for makefiles that is intended to be as
# platform independent as possible.  Where things are platform dependent,
# an if statement is used.
#

F90=lf95
MODULEPATHPREFIX=-I
F90DEBUGFLAGS=-g
INCLUDE=-I/usr/local/TOOLKIT/include
VPATH=..

include ../Makefile.inc

#
# $Log$
# Revision 1.9  2000/02/23 20:34:16  perun
# Changed .o_debug to .dbg.o for SunOS
#
# Revision 1.8  2000/02/22 19:12:45  perun
# Added F90FLAGS for SunOS
#
# Revision 1.7  2000/01/18 15:19:04  perun
# Make solaris same as SunOS
#
# Revision 1.6  1999/12/02 01:56:11  livesey
# Changed filenames to mixed case, redid makefiles.
#
# Revision 1.5  1999/11/04 23:31:27  livesey
# Made the SunOS stuff correct!
#
# Revision 1.4  1999/11/04 23:29:56  livesey
# Added the stuff for SunOS
#
# Revision 1.3  1999/11/04 03:06:49  livesey
# Got the make stuff working I think
#
# Revision 1.2  1999/11/04 02:51:15  livesey
# Fixed bug
#
# Revision 1.1  1999/11/04 02:46:22  livesey
# Added make.inc
#
#
