#Makefile.dep -- a file to be included by a Makefile
#to compile a Fortran 9x program or library
OBJS = \
test_multiply.o  \
\
\
 
# using f90makedep.pl to calculate dependencies 
test_multiply.o: test_multiply.f90 $(dir1)MLSCommon.o $(dir1)MatrixModule_0.o
 
#End of Makefile.dep
 
