#! /usr/bin/perl

# This perl script takes the pcfmapping.dat file and produces an output
# fortran 90 module defining parameters as detailed in the mapping

# Copyright 2005, by the California Institute of Technology. ALL
# RIGHTS RESERVED. United States Government Sponsorship acknowledged. Any
# commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.

# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses, or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.

# "$Id$"
# Check and parse the input parameters

if ($#ARGV != 1) { 
  print "Syntax: makemlspcfmodule <mapping file> <module file>\n"; 
  exit(1);
}

$mappingName=$ARGV[0];
$moduleName=$ARGV[1];
@mod=split(/\./, $moduleName);

# open the input and output files

open (MAPPING, $mappingName) || die "Can't open input mapping file";
open (MODULE, ">$moduleName") || die "Can't open output module file";

print MODULE
    "! Copyright 2005, by the California Institute of Technology. ALL              \n".
    "! RIGHTS RESERVED. United States Government Sponsorship acknowledged. Any     \n".
    "! commercial use must be negotiated with the Office of Technology Transfer    \n".
    "! at the California Institute of Technology.                                  \n".
    "                                                                              \n".
    "! This software may be subject to U.S. export control laws. By accepting this \n".
    "! software, the user agrees to comply with all applicable U.S. export laws and\n".
    "! regulations. User has the responsibility to obtain export licenses, or other\n".
    "! export authority as may be required before exporting such information to    \n".
    "! foreign countries or providing access to foreign persons.                   \n".
    "! NOTE: This module is automatically created by the " . 
    "makemlspcfmodule\n".
    "!       perl script.  Do *NOT* attempt to modify this by hand.\n".
    "!\n".
    "MODULE $mod[0]\n";

# Now go through the input file and read it line by line

$lineCounter=0;

while ($line=<MAPPING>) {
    $lineCounter++;
    
    # Strip comments off the line

    chomp $line;
    $line =~ s/(^[^;]*);.*/$1/;

    # Now if the line contains an = sign it must be a base index assignment

    # if ($line) { print "$line\n";}

    if ($line =~ /=/) {

	# Split into left hand and right hand side
	
	@words= split (/=/,$line);

	if ($#words != 1) {
	    print "Syntax error in mapping file at line $lineCounter\n";
	    exit (1);
	}

	if ($words[0] !~ /baseIndex/i) {
	    print "baseIndex expected at line $lineCounter\n";
	    exit (1);
	}

	# Finish off the old identifier if there was one

	if ($identifier) {
            if($identifier =~ /param/) {
              print MODULE "   !\n";
            }
            else
            {
	    print MODULE outputText($identifier,$baseIndex,
				    $baseIndex+$noFiles-1);
	    }
	    $identifier=0;
	}
#       $baseIndex=$words[1];
        @space = split(/[ +\t]/, $words[1]);
        $baseIndex=$space[0];

    } else {

	# Must be a files line rather than a base index line

	@words= split (" ",$line);

	if ($#words == -1) { next; }

	if ($#words==1) {
	    if (not $identifier) {
		print "Error: Not defined an identifier at line $lineCounter\n";
		exit (1);
	    }
		
	    $filename=$words[0];
	    $noFiles=$noFiles+$words[1];

            if($identifier =~ /param/) {
              $name = join("_",$identifier,$filename);
              $num = $baseIndex+$noFiles-1;
              print MODULE "   INTEGER, PARAMETER :: mlspcf_$name = $num\n";
            }

	}
	elsif ($#words==2) 
	{
	    # This is a new identifier, write out the information on
	    # the previous one if there was one.

	    if ($identifier) {
		print MODULE outputText($identifier,$baseIndex,
		   			$baseIndex+$noFiles-1);
	 	$baseIndex=$baseIndex+$noFiles;
		$identifier=0;
	    }
	    $identifier=$words[0];

	    if ($identifier !~ /\w+:/) {
		print ": expected at line $lineCounter\n";
		print "$line\n";
		exit (1);
	    }

	    $identifier =~ s/(\w+):/$1/;
	    $filename=$words[1];
	    $noFiles=$words[2];

            if($identifier =~ /param/) {
              $name = join("_",$identifier,$filename);
              $num = $baseIndex+$noFiles-1;
              print MODULE "   INTEGER, PARAMETER :: mlspcf_$name = $num\n";
            }

	}
	else
	{
	    print "Wrong number of words at line $lineCounter\n";
	    print "$line\n";
	    print "Got $#words words.\n";
	    exit (1);
	}
    }
}

print MODULE "END MODULE $mod[0]\n";

close (MAPPING);
close (MODULE);

exit;

sub outputText {
   "   INTEGER, PARAMETER :: mlspcf_$_[0]_start = $_[1]\n".
   "   INTEGER, PARAMETER :: mlspcf_$_[0]_end = $_[2]\n".
   "   !\n"
   }
# $Log$
