# $Id$

# Fortran compiler:
FC = lf95

# Compiler options:
FOPTS = -g --chk

# Loader options:
LDOPTS = -g --chk

# Path to source files:
S = ..

# Option to specify path to .mod files:
I = -I

# Path to .mod files for MLS library:
M = $(HOME)/mlspgs/lib/LF95

# SDPToolkit or SDPToolkitSubstitute?
#SDP = 
SDP = Substitute

include ../Makefile.inc

# $Log$
# Revision 2.1  2000/10/09 23:25:35  vsnyder
# Introduce SDP variable
#
# Revision 2.0  2000/09/05 17:42:01  dcuddy
# Change revision to 2.0
#
# Revision 1.2  2000/07/06 18:04:05  vsnyder
# Insert CVS "variables"
#
