#!/bin/sh
#                 mlsconfigure    configures the mls for compiler, platform
#
#
# Called for either or both of two purposes:
#
# (1) Query user for: 
#     (a) compiler and platform; 
#     (b) SDP, HDF, HDF-EOS paths; 
#     (c) paths to PVM and FFTW libraries; 
#     
#     ((1)not done if I am called with -nc option)
#     these get written to .configure
# (2) Create a new directory ./$MLSCONFG in parallel with ./platforms; then
#     put Makefile in it created from appropriate 2 files in platforms;
#     e.g., say $MLSCONFG is NAG.Linux
#     this Makefile will then contain the following lines:
#        # 1st: lines from .configure file
#        MLSF90=NAG
#        MLSPLAT=Linux
#        # 2nd: lines from platforms/NAG.Linux
#        FC=f95
#         (etc.)
#        # Last: lines from platforms/targets
#        PROG=mlsl2
#        $(PROG): $(OBJS) $(libdir)/libmls.a
#         (etc.)
#
#     *.o, *.mod, etc. files will go in this new directory
#     ((2) not done if ./platforms directory fails to exist)
#
#        O p t i o n s
#  -h[elp]              (if present) Help (not yet fully implemented)
#  -c compiler_name     Name of Fortran compiler (NAG or LF95)
#  -p platform_name     Name of computer or OS (Linux , sun, or sgi)
#  -dc conf_dir         Directory where .configuration file is to be stored
#  -pc plat_dir         Directory where platforms directory to be found
#  -nc                  (if present) Don't query nor change configuration
#  -nd                  (if present) Don't delete ./$MLSCONFG if it already exists
#  -pv                  (if present) Change PVM and FFTW settings
#  -fl                  (if present) Change default FOPTS and LDOPTS
#
# Copyright (c) 1999, California Institute of Technology.  ALL RIGHTS RESERVED.
# U.S. Government Sponsorship under NASA Contract NAS7-1407 is acknowledged.

# "$Id$"

#------------------------------- UserPrompt ------------
# Function to prompt for user response
#

UserPrompt()
{
    if [ "$BRAND" = "linux" ] ; then
	/bin/echo -n "$* " > /dev/tty
    else
	echo "$* \\c" > /dev/tty
    fi
    read user_response
}

#------------------------------- GetPlatform ------------

GetPlatform()
{
        more << EOF_1
                    *        *        *

The mls software requires that you configure it by responding to two
questions; currently your platform and compiler are given by:

        platform: $current_platform
        compiler: $current_compiler

If these settings are wrong, or you wish to change them in order to
prepare multiple installations at your site, you will be given an
opportunity to (re)set them momentarily.

If your compiler or platform is not among the options to be presented,
you may wish to try one of the options anyway, or else contact:

	mls software team
	jpl
	David.T.Cuddy@jpl.nasa.gov
	(818)354-2099

and give the names of the compiler and platform you use.

                    *        *        *

Note that you must have a Fortran 95 or later compiler, and that you
must first have installed the SDP Toolkit for the ECS Project. The
latter, as well as useful documentation, may be obtained from the
management of the EOSDIS Core System Data Handling System. At the time
this configuration was being written (17 Oct 2000), the URL for them was
	http://edhs1.gsfc.nasa.gov/

EOF_1

#accept user compiler and platforms settings to be written to file .configure

 UserPrompt "Fortran 95 Compiler (Lahey, NAG, absoft) [$current_compiler]"
   if [ "$user_response" != "" ] ; then
	case  "$user_response" in
	    n* | N* )
		echo "NAG compiler selected."
		compiler=NAG
	    ;;
	    l* | L* )
		echo "Lahey compiler selected."
		compiler=LF95
	    ;;
	    a* | A* )
		echo "Absoft compiler selected."
		compiler=Abs
	    ;;
	    * )
		echo "Unknown compiler selected."
		compiler=Unknown
	    ;;
	esac
   elif [ "$current_compiler" != "" ] ; then
	echo "Compiler still $current_compiler."
        compiler=$current_compiler
   else
	echo "Unknown compiler selected."
	compiler=Unknown
    fi

 UserPrompt "Platform (Linux, Sun, SGI) [$current_platform]"
   if [ "$user_response" != "" ] ; then
	case  "$user_response" in
	    su* | Su* | SU*)
		echo "Sun platform selected."
		platform=Sun
	    ;;
	    sg* | Sg* | SG* )
		echo "SGI platform selected."
		platform=SGI
	    ;;
	    l* | L* )
		echo "Linux platform selected."
		platform=Linux
	    ;;
	    * )
		echo "No platform selected."
		platform=None
	    ;;
	esac
   elif [ "$current_platform" != "" ] ; then
	echo "Platform still $current_platform."
        platform=$current_platform
   else
	echo "No platform selected."
	platform=None
   fi

export platform
export compiler

        more << EOF_2
                    *        *        *

To properly link the mls software requires that you set the paths to
the libraries installed along with the SDP Toolkit. If you don't know these
locations, you might have to ask the person at your site who installed
this toolkit. It is possible that during the installation, these paths
were automatically "hard wired" as environment variables, and if so the
values shown below will be correct. If they are correct, simply answer
Y[es] to the next question. Otherwise you will be asked to supply the
correct paths.

Note: a path is a length of test that looks something like this:
    /head/Toolkit/lib/linux
would correspond to the path to the SDP Toolkit (called just "toolkit")

EOF_2

all_non_blank="true"

if [ "$current_PGSINC" = "" ] ; then
	all_non_blank="false"
elif [ "$current_PGSTK" = "" ] ; then
	all_non_blank="false"
elif [ "$current_HDFEOS" = "" ] ; then
	all_non_blank="false"
elif [ "$current_HDF" = "" ] ; then
	all_non_blank="false"
elif [ "$current_GCTP" = "" ] ; then
	all_non_blank="false"
fi

if [ "$all_non_blank" = "true" ] ; then

        more << EOF_3
Currently your paths are given by:

        "include" files:  $current_PGSINC
        toolkit:          $current_PGSTK
        hdf-eos:          $current_HDFEOS
        hdf:              $current_HDF
        gctp:             $current_GCTP

If any of these settings are wrong or blank, or you wish to change them in
order to prepare multiple installations at your site, you will be given an
opportunity to (re)set them momentarily.

EOF_3

 UserPrompt "Are all of these paths correct and non-blank?[Y[es] or N[o]]"
   if [ "$user_response" != "" ] ; then
	case  "$user_response" in
	    n* | N* )
		change_paths="true"
	    ;;
	    y* | Y* )
		change_paths="false"
	    ;;
	esac
   else
	change_paths="false"
    fi

else
		change_paths="true"
fi

if [ $change_paths = "true" ] ; then
#Change Includes path
 UserPrompt "include files path [$current_PGSINC]"
   if [ "$user_response" != "" ] ; then
	 PGSINC=$user_response
   elif [ "$current_PGSINC" != "" ] ; then
	echo "include files path is still $current_PGSINC."
        PGSINC=$current_PGSINC
   else
	echo "Warning: No include files path selected; none found"
	echo "mls software may not compile properly "
	echo "unless you reconfigure; enter 'make configure'."
	PGSINC="/"
   fi

#Change Toolkit path
 UserPrompt "Toolkit path [$current_PGSTK]"
   if [ "$user_response" != "" ] ; then
	 PGSTK=$user_response
   elif [ "$current_PGSTK" != "" ] ; then
	echo "Toolkit path is still $current_PGSTK."
        PGSTK=$current_PGSTK
   else
	echo "Warning: No toolkit path selected; none found"
	echo "mls software may not link properly "
	echo "unless you reconfigure; enter 'make configure'."
	PGSTK="/"
   fi

#Change hdfeos path
 UserPrompt "HDFEOS path [$current_HDFEOS]"
   if [ "$user_response" != "" ] ; then
	 HDFEOS=$user_response
	 current_GCTP=$user_response
	 GCTP=$user_response
   elif [ "$current_HDFEOS" != "" ] ; then
	echo "Toolkit path is still $current_HDFEOS."
        HDFEOS=$current_HDFEOS
   else
	echo "Warning: No HDFEOS path selected; none found"
	echo "mls software may not link properly "
	echo "unless you reconfigure; enter 'make configure'."
	HDFEOS="/"
   fi

#Change hdf path
 UserPrompt "HDF path [$current_HDF]"
   if [ "$user_response" != "" ] ; then
	 HDF=$user_response
   elif [ "$current_HDF" != "" ] ; then
	echo "Toolkit path is still $current_HDF."
        HDF=$current_HDF
   else
	echo "Warning: No HDF path selected; none found"
	echo "mls software may not link properly "
	echo "unless you reconfigure; enter 'make configure'."
	HDF="/"
   fi

#Change gctp path
 UserPrompt "GCTP path [$current_GCTP]"
   if [ "$user_response" != "" ] ; then
	 GCTP=$user_response
   elif [ "$current_GCTP" != "" ] ; then
	echo "Toolkit path is still $current_GCTP."
        GCTP=$current_GCTP
   else
	echo "Warning: No GCTP path selected; none found"
	echo "mls software may not link properly "
	echo "unless you reconfigure; enter 'make configure'."
	GCTP="/"
   fi

else
    PGSINC=$current_PGSINC
    PGSTK=$current_PGSTK
    HDFEOS=$current_HDFEOS
    HDF=$current_HDF
    GCTP=$current_GCTP
fi
}

#------------------------------- GetPVM ------------
GetPVM()
{

if [ "$add_PVM_PATH" != "true" ] ; then
	change_paths="false"
else
        more << EOF_4
                    *        *        *

The next questions refer to two special libraries: PVM and FFTW. Here too,
it is possible that during the installation, these paths were automatically
"hard wired" as environment variables, and if so the values shown below may be
correct. If they are correct, simply answer Y[es] to the next question.
Otherwise you will be asked to supply the correct paths.

Currently these paths are given by:

        PVM root       :  $current_PVM_ROOT
        FFTW path      :  $current_FFTW_ROOT

If these settings are wrong, or you wish to change them in order to prepare
multiple installations at your site, you will be given an opportunity to
(re)set them momentarily.

Note that if you wish to "unset" any, that is to give them blank values, you
cannot simply hit enter when asked to supply the new value because that means
"continue using the existing value" which is what you want only if the existing
value is already blank. Instead, to unset a non-blank exisiting value, enter
"<b>" (w/o the " marks).
EOF_4

 UserPrompt "Are these paths correct [Y[es] or N[o]]"
   if [ "$user_response" != "" ] ; then
	case  "$user_response" in
	    n* | N* )
		change_paths="true"
	    ;;
	    y* | Y* )
		change_paths="false"
	    ;;
	esac
   else
	change_paths="false"
    fi

fi

if [ $change_paths = "true" ] ; then
#Change PVM root path
 UserPrompt "PVM root (enter <b> to force back to blank) [$current_PVM_ROOT]"
   if [ "$user_response" = "<b>" ] ; then
	 PVM_ROOT=""
	 echo "You will build a mls software version without PVM support"
   elif [ "$user_response" != "" ] ; then
	 PVM_ROOT=$user_response
   elif [ "$current_PVM_ROOT" != "" ] ; then
	echo "PVM root path is still $current_PVM_ROOT."
        PVM_ROOT=$current_PVM_ROOT
   else
	echo "Warning: No PVM ROOT path selected; none found"
	echo "You will build a mls software version without PVM support"
	echo "unless you reconfigure; enter 'make configure'."
	PVM_ROOT=""
   fi

#Change FFTW root path
 UserPrompt "FFTW root (enter <b> to force back to blank) [$current_FFTW_ROOT]"
   if [ "$user_response" = "<b>" ] ; then
	 FFTW_ROOT=""
	 echo "You will build a mls software version without FFTW support"
   elif [ "$user_response" != "" ] ; then
	 FFTW_ROOT=$user_response
   elif [ "$current_FFTW_ROOT" != "" ] ; then
	echo "FFTW path is still $current_FFTW_ROOT."
        FFTW_ROOT=$current_FFTW_ROOT
   else
	echo "Warning: No FFTW root path selected; none found"
	echo "The level 3 mls software will not link properly"
	echo "unless you reconfigure; enter 'make configure'."
	FFTW_ROOT=""
   fi

else
    PVM_ROOT=$current_PVM_ROOT
#    PVM_ARCH=$current_PVM_ARCH
    FFTW_ROOT=$current_FFTW_ROOT
fi

#PVM arch is based on platform
#platform        PVM_ARCH
#  Sun           SUN4SOL2
#  SGI            SGI6
#  Linux         LINUX
#  None          LINUX

if [ "$platform" = "Sun" ] ; then
	PVM_ARCH="SUN4SOL2"
elif [ "$platform" = "SGI" ] ; then
	PVM_ARCH="SGI6"
else
	PVM_ARCH="LINUX"
fi
}

#------------------------------- GetFOPTS ------------

GetFOPTS()
{
        more << EOF_5
                    *        *        *

You may change the current options passed to the compiler and linker. Normally
the default options work well, but you may wish to set debugging, turn on
warning messages, or choose advanced optimizations. Consult your manual for
the precise format before changing these. 

To reset an option to its default enter the word "default" (w/o the " marks)
at the prompt.

EOF_5

#accept user compiler/linker options to be written to file .configure

 UserPrompt "Fortran 95 Compiler options [$current_FOPTS]"
   if [ "$user_response" = "default" ] ; then
		current_FOPTS=
   elif [ "$user_response" != "" ] ; then
		current_FOPTS="$user_response"
	fi

 UserPrompt "Fortran 95 Linker options [$current_LDOPTS]"
   if [ "$user_response" = "default" ] ; then
		current_LDOPTS=
   elif [ "$user_response" != "" ] ; then
		current_LDOPTS="$user_response"
	fi

}

#------------------------------- Help ------------
#
# Function to output brief help message and exit
#

Help()
{

        more << EOF_6
                    *        *        *

In order to properly build the mls software, a configuration step is required.
Normally this is done only once: immediately after un-tarring or copying the
source onto your machine. However in case of trouble, to optimize speed, or for
other reasons this may need to be done again.

The configuration step can be subdivided into three sub-steps: the first is
basic and an absolute prerequisite; the other two are optional
(i)    Identify your compiler, platform type, and paths to installed libraries
       of HDF, HDFEOS, and Toolkits. This is the most basic info and you will
       automatically be prompted for it. To change these settings later,
       enter "make -f MakeFC configure"
(ii)   Decide if you want to build the software with support for PVM and FFTW.
       The first may improve performance,  while the second is needed to build
       level 3. These require setting paths to installed libraries of PVM and
       FFTW software. To learn where to obtain them, enter "BEFORE.mls". To 
       change these settings later, enter "make -f MakeFC configure_pvm"
(iii)  Choose compiler and linker options. Although these are automatically
       set to default values that work well, you may have a reason to prefer
       different options.To change these settings later,
       enter "make -f MakeFC configure_fopts"
		 
EOF_6

#No further help available yet
    exit
}

#------------------------------- Main Program ------------

#****************************************************************
#                                                               *
#                  * * * Main Program  * * *                    *
#                                                               *
#                                                               *
#	The entry point where control is given to the script         *
#****************************************************************

# Set the following to "on" to print degugging info
debugging="off"

#Default compiler and linker options
MLS_default_FOPTS_NAG="-w"
MLS_default_FOPTS_LF95=
MLS_default_FOPTS_Abs="-w"
MLS_default_LDOPTS=

#conf_dir   the directory where the .configure file is to be stored
#plat_dir   the directory to keep the platforms subdirectories
#get_confg  true if user queried about configuration; false if use input values
conf_dir="./"
plat_dir="./"
get_confg="true"
del_exist_dir="true"

current_compiler=$MLSF95
current_platform=$MLSPLAT

current_PGSINC=$PGSINC
current_PGSTK=$PGSLIB
current_HDFEOS=$HDFEOS_LIB
current_HDF=$HDFLIB
current_GCTP=$HDFEOS_LIB

# Whether to include PVM & FFTW paths in .configure
add_PVM_PATH="false"
current_PVM_ROOT=$PVM_ROOT
current_PVM_ARCH=$PVM_ARCH
current_FFTW_ROOT=$FFTW_ROOT

# Whether to include default FOPTS and LDOPTS in .configure
add_FOPTS="false"
current_FOPTS=$FOPTS
current_LDOPTS=$LDOPTS

# Debugging
if [ "$debugging" = "on" ] ; then
	echo "MLSF95=$MLSF95"
	echo "MLSPLAT=$MLSPLAT"
	echo "PGSINC=$PGSINC"
	echo "PGSLIB=$PGSLIB"
	echo "HDFEOS_LIB=$HDFEOS_LIB"
	echo "HDFLIB=$HDFLIB"
	echo "add_PVM_PATH=$add_PVM_PATH"
	echo "PVM_ROOT=$PVM_ROOT"
	echo "PVM_ARCH=$PVM_ARCH"
	echo "FFTW_ROOT=$FFTW_ROOT"
	echo "FOPTS=$FOPTS"
	echo "LDOPTS=$LDOPTS"
fi

#
# Get arguments from command line
#

me="$0"

while [ "$1" != "" ] ; do

    case "$1" in

	-h | -help )
#            sed -n '2, 35 p' $me
	    Help
            exit
	;;

	-c )
	    current_compiler=$2
	    shift
	;;

	-p )
	    current_platform=$2
	    shift
	;;

	-dc )
	    conf_dir=$2
	    shift
	;;

	-pc )
	    plat_dir=$2
	    shift
	;;

	-nc )
	    get_confg="false"
	;;

	-nd )
	    del_exist_dir="false"
	;;

	-pv )
	    add_PVM_PATH="true"
	;;

	-fl )
	    add_FOPTS="true"
	;;

    esac
    shift

done

write_confg="false"

if [ $get_confg = "true" ] ; then
	GetPlatform
	write_confg="true"
else
        compiler=$current_compiler
        platform=$current_platform
 fi

if [ $add_PVM_PATH = "true" ] ; then
	GetPVM
	write_confg="true"
fi

if [ $add_FOPTS = "true" ] ; then
	GetFOPTS
	write_confg="true"
fi

if [ "$current_FOPTS" = "" ] ; then
		if [ "$compiler" = "NAG" ] ; then
			FOPTS="$MLS_default_FOPTS_NAG"
		elif [ "$compiler" = "Abs" ] ; then
			FOPTS="$MLS_default_FOPTS_Abs"
		else
			FOPTS="$MLS_default_FOPTS_LF95"
		fi
else
	FOPTS=$current_FOPTS
fi

if [ "$current_LDOPTS" = "" ] ; then
			LDOPTS="$MLS_default_LDOPTS"
else
	LDOPTS=$current_LDOPTS
fi

if [ $write_confg = "true" ] ; then
# 1st--check on blank paths
# if blank, attempt alternate settings
# if that fails, echo regrets and abort
	if [ "$PGSTK" = "" ] ; then
		PGSTK=$PGSLIB
	fi
	if [ "$PGSTK" = "" ] ; then
		echo " Sorry--the toolkit path must not be blank"
		exit
	fi
	
	if [ "$HDF" = "" ] ; then
		HDF=$HDFLIB
	fi
	if [ "$HDF" = "" ] ; then
		echo " Sorry--the HDF path must not be blank"
		exit
	fi
	
	if [ "$HDFEOS" = "" ] ; then
		HDFEOS=$HDFEOS_LIB
	fi
	if [ "$HDFEOS" = "" ] ; then
		echo " Sorry--the HDFEOS path must not be blank"
		exit
	fi
	
	if [ "$GCTP" = "" ] ; then
		GCTP=$HDFEOS_LIB
	fi
	if [ "$GCTP" = "" ] ; then
		echo " Sorry--the GCTP path must not be blank"
		exit
	fi
	
#	Create .configure file
	if [ -f $conf_dir/.configure ] ; then
		chmod u+w $conf_dir/.configure
		rm -f $conf_dir/.configure
	fi

	echo "#	.configure for mls" > $conf_dir/.configure
	echo "MLSF95=$compiler" >> $conf_dir/.configure
	echo "MLSPLAT=$platform" >> $conf_dir/.configure
	echo "MLSCONFG=$compiler.$platform" >> $conf_dir/.configure
	echo "PGSINC=$PGSINC" >> $conf_dir/.configure
	echo "PGSTK=$PGSTK" >> $conf_dir/.configure
	echo "HDFEOS=$HDFEOS" >> $conf_dir/.configure
	echo "HDF=$HDF" >> $conf_dir/.configure
	echo "GCTP=$GCTP" >> $conf_dir/.configure
	echo "PGSLIB=$PGSTK" >> $conf_dir/.configure
	echo "HDFEOS_LIB=$HDFEOS" >> $conf_dir/.configure
	echo "HDFLIB=$HDF" >> $conf_dir/.configure
	echo "PVM_ROOT=$PVM_ROOT" >> $conf_dir/.configure
	echo "PVM_ARCH=$PVM_ARCH" >> $conf_dir/.configure
	echo "FFTW_ROOT=$FFTW_ROOT" >> $conf_dir/.configure
	echo "FOPTS=$FOPTS" >> $conf_dir/.configure
	echo "LDOPTS=$LDOPTS" >> $conf_dir/.configure
	echo "export MLSF95" >> $conf_dir/.configure
	echo "export MLSPLAT" >> $conf_dir/.configure
	echo "export MLSCONFG" >> $conf_dir/.configure
	echo "export PGSINC" >> $conf_dir/.configure
	echo "export PGSLIB" >> $conf_dir/.configure
	echo "export HDFEOS_LIB" >> $conf_dir/.configure
	echo "export HDFLIB" >> $conf_dir/.configure
	echo "export PGSTK" >> $conf_dir/.configure
	echo "export HDFEOS" >> $conf_dir/.configure
	echo "export HDF" >> $conf_dir/.configure
	echo "export GCTP" >> $conf_dir/.configure
	echo "export PVM_ROOT" >> $conf_dir/.configure
	echo "export PVM_ARCH" >> $conf_dir/.configure
	echo "export FFTW_ROOT" >> $conf_dir/.configure
	echo "export FOPTS" >> $conf_dir/.configure
	echo "export LDOPTS" >> $conf_dir/.configure
else
#	just re-use current settings
	compiler=$current_compiler
	platform=$current_platform
fi

MLSF95=$compiler
MLSPLAT=$platform
MLSCONFG=$compiler.$platform
export MLSF95
export MLSPLAT
export MLSCONFG

if [ $get_confg = "true" ] ; then
	echo "MLSF95 is now $MLSF95"
	echo "MLSPLAT is now $MLSPLAT"
	echo "MLSCONFG is now $MLSCONFG"
fi

if [ $add_PVM_PATH = "true" ] ; then
	echo "PVM_ROOT is now $PVM_ROOT"
	echo "PVM_ARCH is now $PVM_ARCH"
	echo "FFTW_ROOT is now $FFTW_ROOT"
fi

if [ $add_FOPTS = "true" ] ; then
	echo "FOPTS is now $FOPTS"
	echo "LDOPTS is now $LDOPTS"
fi

#Don't create object-file directory if platforms not a directory
if [ ! -d $plat_dir/platforms ] ; then
	exit
fi

#Create object-file directory for this MLSCONFG
#unless $del_exist_dir reset to false
# Because mlsconfigure may be called simply to update $MLSCONFG/Makefile
made_new_dir="false"

if [ "$MLSCONFG" = "." ] ; then
	echo "MLSCONFG not yet defined--still $MLSCONFG"
elif [ "$del_exist_dir" != "true" ] ; then
	if [ ! -d $plat_dir/$MLSCONFG ] ; then
        mkdir $plat_dir/$MLSCONFG
			made_new_dir="true"
	fi
elif [ -d $plat_dir/$MLSCONFG ] ; then
#	echo "Clearing out directory `pwd`$plat_dir/$MLSCONFG"
#	echo "(Be careful that this is not too ambitious)"
	chmod u+w $plat_dir/$MLSCONFG/*
#	rm -f $plat_dir/$MLSCONFG/*.o
#	rm -f $plat_dir/$MLSCONFG/*.mod
#	rm -f $plat_dir/$MLSCONFG/Makefile
	rm -f $plat_dir/$MLSCONFG/*
else
        mkdir $plat_dir/$MLSCONFG
			made_new_dir="true"
fi

if [ ! -f $plat_dir/platforms/$MLSCONFG ] ; then
	echo "File $MLSCONFG not found in $plat_dir/platforms"
	exit
fi

if [ ! -f $plat_dir/platforms/targets ] ; then
	echo "File targets not found in $plat_dir/platforms"
	exit
fi

cat $conf_dir/.configure $plat_dir/platforms/$MLSCONFG $plat_dir/platforms/targets > $plat_dir/$MLSCONFG/Makefile

if [ "$made_new_dir" = "true" ] ; then
	echo "Configured mls to use $plat_dir/platforms/$MLSCONFG "
	echo "(This is where your object files, .mod files, libraries,"
	echo "and executable programs will be created)"
	echo "To build the software, enter the 'make' command again"
	echo ""
	echo "If you later wish to rebuild for a different compiler"
	echo "or platform, enter 'make configure'"
fi

exit
# $Log$
# Revision 1.8  2001/02/27 18:10:44  pwagner
# exports FOPTS and LDOPTS; better Help
#
# Revision 1.7  2001/02/26 18:39:15  pwagner
# Fixed problem with older .configure files
#
# Revision 1.6  2001/02/26 00:26:49  pwagner
# default FOPTS and LDOPTS can be set,  saved to .configure
#
# Revision 1.5  2001/02/10 00:06:47  pwagner
# update now a target of make -f MakeFC; replaces customized Makefiles with latest versions
#
# Revision 1.4  2001/01/23 19:41:36  pwagner
# Adds support for PVM
#
# Revision 1.3  2000/10/21 00:23:58  pwagner
# Added paths to .configure
#
# Revision 1.2  2000/10/18 20:56:21  pwagner
# Fixed obvious bug; 1st step towards -h option
#
# Revision 1.1  2000/10/16 18:31:19  pwagner
# first commit
#

