#!/bin/sh
# --------------- mlsconfigure help
#                 mlsconfigure    configures the mls for compiler, platform
#
# Called for either or both of two purposes:
#
# (1) Query user for: 
#     (a) compiler and platform; 
#     (b) SDP, HDF, HDF-EOS paths; 
#     (c) paths to BLAS, LAPACK, PVM and FFTW (the "pv") libraries; 
#     
#     ((1)not done if I am called with -nc option)
#     these get written to .configure
# (2) Create a new directory $mcfg_dir/$MLSCONFG
#      in parallel with $plat_dir/platforms; then
#     put Makefile in it created from appropriate 2 files in platforms;
#     e.g., say $MLSF95.$MLSPLAT is NAG.Linux
#     this Makefile will then contain the following lines:
#        # 1st: lines from .configure file
#        MLSF90=NAG
#        MLSPLAT=Linux
#        # 2nd: lines from platforms/NAG.Linux
#        FC=f95
#         (etc.)
#        # Last: lines from platforms/targets
#        PROG=mlsl2
#        $(PROG): $(OBJS) $(libdir)/libmls.a
#         (etc.)
#
#     *.o, *.mod, etc. files will go in this new directory
#     ((2) not done if $plat_dir/platforms directory fails to exist)
#
#        O p t i o n s
#  -h[elp]              (if present) Help (a work in progress)
#  -help--brief         Brief overview
#  -help--mlsconfigure  Help on mlsconfigure script
#  -c compiler_name     Name of Fortran compiler (Absoft, NAG, LF95, Sun)
#  -confg confg_name    Name of configuration (chosen by user)
#  -p platform_name     Name of computer or OS (Linux , sun, or sgi)
#  -dc conf_dir         Directory where .configuration file is to be stored
#  -pc plat_dir         Directory where platforms directory to be found
#                        (defaults to ./)
#  -mc mcfg_dir         Directory where $MLSCONFG directory will be created
#                        (defaults to ./)
#  -nc                  (if present) Don't query nor change configuration
#  -nd                  (if present) Don't delete ./$MLSCONFG if it already exists
#  -pv                  (if present) Change PVM and FFTW settings
#  -fl                  (if present) Change default FOPTS and LDOPTS
#  -cf file_name        (if present) Use file_name instead of .configure
# --------------- End mlsconfigure help
#
# Copyright (c) 2001, California Institute of Technology.  ALL RIGHTS RESERVED.
# U.S. Government Sponsorship under NASA Contract NAS7-1407 is acknowledged.

# "$Id$"

#------------------------------- UserPrompt ------------
# Function to prompt for user response
#

UserPrompt()
{
#    if [ "$BRAND" = "linux" ] ; then
    if [ "$OSTYPE" = "linux" ] ; then
	/bin/echo -n "$* " > /dev/tty
    else
	echo "$* \\c" > /dev/tty
    fi
    read user_response
}

#------------------------------- eecchhoo ------------
# Function to echo each of its args on a separate line
# unless there are no args, in which case echo the
# current definition of BLANKLINE

eecchhoo()
{
    if [ "$#" = 0 ] ; then
	    echo $BLANKLINE
    else
       for line
       do
	       echo "$line"
       done
    fi
}

#------------------------------- which_blas ------------
#
# Function to determine Which of possible BLAS options {a b c} is active
# usage: which_blas $BLAS $LIB_BLAS
# returns which_blas_option and which_blas_msg

which_blas()
{

if [ "$1" != "" ] ; then
#  Use externally-supplied library to satisfy blas calls
	which_blas_msg="$1/lib${2}.a"
	which_blas_option="a"
elif [ "$2" = "f95" ] ; then
#  Use f95 intrinsic functions
	which_blas_msg="(Use f95 intrinsic functions for any BLAS routines)"
	which_blas_option="b"
else
#  Let the mls software build its own BLAS routines
	which_blas_msg="(Let the mls software build its own BLAS routines)"
	which_blas_option="c"
fi

}

#------------------------------- which_lapack ------------
#
# Function to determine Which of possible lapack options {a b} is active
# usage: which_lapack $LAPACK $LIB_LAPACK
# returns which_lapack_option and which_lapack_msg

which_lapack()
{

if [ "$1" != "" ] ; then
#  Use externally-supplied library to satisfy lapack calls
#	which_lapack_msg="$1/lib${2}.a"
   which_lapack_msg=`$REECHO -dir $1 -prefixn=-l -lib $2`
   which_lapack_msg="-L$1 ${which_lapack_msg}"
	which_lapack_option="a"
else
#  Use f95 intrinsic functions
	which_lapack_msg="(Use f95 intrinsic functions for any lapack routines)"
	which_lapack_option="b"
fi

}

#------------------------------- mega_buck ------------
#
# Function to force multiple-evaluation of its second arg
# i.e., $$..$color (where the number of $ signs is n)
# usage: mega_buck n color

mega_buck()
{

   # Trivial case (n is 0)
   if [ "$1" -lt 1 ]
      then
         mega_buck_result="$2"
   elif [ "$2" = "" ]
      then
         mega_buck_result="$2"
   # Do we have write permission in ./?
   elif [ ! -w "./" ]
      then
         echo "Sorry--need write permission in ./ to operate"
         exit 1
   else
      
      rm -f temp.mega_buck

      number=0
      mega_buck_result=$2
      while [ "$number" -lt "$1" ]
      do
         echo "echo \$arg" | sed 's/arg/'$mega_buck_result'/' > temp.mega_buck
         mega_buck_result=`. temp.mega_buck`
         rm -f temp.mega_buck
         number=`expr $number + 1`
      done
   fi
}

#------------------------------- GetPlatform ------------

GetPlatform()
{
        more << EOF_1
                    *        *        *

The mls software requires that you configure it by responding to some
questions; currently your platform, compiler and configuration name are given
by:

        platform:           $current_platform
        compiler:           $current_compiler
        configuration name: $current_confg

If these settings are wrong, or you wish to change them in order to
prepare multiple installations at your site, you will be given an
opportunity to (re)set them momentarily.

If your compiler or platform is not among the options to be presented,
you may wish to try one of the options anyway, or else contact:

	mls software team
	jpl
	David.T.Cuddy@jpl.nasa.gov
	(818)354-2099

and give the names of the compiler and platform you use.

The name you choose for your configuration can reflect the choice of settings
embodied in it. The default offered to you, based on the compiler and platform,
should be accepted unless you intend to maintain multiple configurations
simultaneously with different compiler or linker options, linked libraries, and
so on.

                    *        *        *

Note that you must have a Fortran 95 or later compiler, and that you
must first have installed the SDP Toolkit for the ECS Project. The
latter, as well as useful documentation, may be obtained from the
management of the EOSDIS Core System Data Handling System. At the time
this configuration was being written (17 Oct 2000), the URL for them was
	http://edhs1.gsfc.nasa.gov/

EOF_1

#accept user compiler and platforms settings to be written to file .configure

   eecchhoo "" "f 9 5"
 UserPrompt "Fortran 95 Compiler (Lahey, NAG, absoft, Sun) [$current_compiler]"
   if [ "$user_response" != "" ] ; then
	case  "$user_response" in
	    n* | N* )
		echo "NAG compiler selected."
		compiler=NAG
	    ;;
	    l* | L* )
		echo "Lahey compiler selected."
		compiler=LF95
	    ;;
	    a* | A* )
		echo "Absoft compiler selected."
		compiler=Abs
	    ;;
	    s* | S* )
		echo "Sun's own (*not* NAG) f95 compiler selected."
		compiler=Sun
	    ;;
	    * )
		echo "Unknown compiler selected."
		compiler=Unknown
	    ;;
	esac
   elif [ "$current_compiler" != "" ] ; then
	echo "Compiler still $current_compiler."
        compiler=$current_compiler
   else
	echo "Unknown compiler selected."
	compiler=Unknown
    fi

#Check if changed compiler
   if [ "$compiler" != "$current_compiler" ] ; then
		chngd_confg="true"
	fi

   eecchhoo "" "p l a t f o r m"
 UserPrompt "Platform (Linux, Sun, SGI) [$current_platform]"
   if [ "$user_response" != "" ] ; then
	case  "$user_response" in
	    su* | Su* | SU*)
		echo "Sun platform selected."
		platform=Sun
	    ;;
	    sg* | Sg* | SG* )
		echo "SGI platform selected."
		platform=SGI
	    ;;
	    l* | L* )
		echo "Linux platform selected."
		platform=Linux
	    ;;
	    * )
		echo "No platform selected."
		platform=None
	    ;;
	esac
   elif [ "$current_platform" != "" ] ; then
	echo "Platform still $current_platform."
        platform=$current_platform
   else
	echo "No platform selected."
	platform=None
   fi

#Check if changed platform
   if [ "$platform" != "$current_platform" ] ; then
		chngd_confg="true"
	fi

   if [ "$chngd_confg" = "true" ] ; then
		current_confg="$compiler.$platform"
	fi
   eecchhoo "" "c o n f i g u r a t i o n   n a m e"
	echo "You may choose either a custom name or accept the default name"
 UserPrompt "Name [$current_confg]"
   if [ "$user_response" != "" ] ; then
      MLSCONFG="$user_response"
   elif [ "$current_confg" != "" ] ; then
	echo "Defaulting to the name $current_confg."
        MLSCONFG=$current_confg
   else
	   echo "(This should not have happened--no name possible)"
	   MLSCONFG="."
   fi

#Check if changed configuration name
#(Don't worry about current_platform being different from the old one
#--if that happened it was because chngd_confg was already true anyway)
   if [ "$MLSCONFG" != "$current_confg" ] ; then
		chngd_confg="true"
	fi

export platform
export compiler

        more << EOF_2
                    *        *        *

To properly link the mls software requires that you set the paths to the
libraries installed along with the SDP Toolkit. If you don't know these
locations, you might have to ask the person at your site who installed this
toolkit. It is possible that during the installation, these paths were
automatically "hard wired" as environment variables, and if so the values shown
below will be correct. If they are correct, simply answer Y[es] to the next
question. Otherwise you will be asked to supply the correct paths. Except for
hdf-eos(5) and hdf(5), all paths must be non-blank.

Note: a path is a length of test that looks something like this:
    /head/Toolkit/lib/linux
would correspond to the path to the SDP Toolkit (called just "toolkit")

EOF_2

all_non_blank="true"

if [ "$current_PGSINC" = "" ] ; then
	all_non_blank="false"
elif [ "$current_PGSTK" = "" ] ; then
	all_non_blank="false"
elif [ "$current_HDFEOS" = "" ] ; then
	all_non_blank="false"
elif [ "$current_HDF" = "" ] ; then
	all_non_blank="false"
elif [ "$current_GCTP" = "" ] ; then
	all_non_blank="false"
fi

if [ "$all_non_blank" = "true" ] ; then

        more << EOF_3
Currently your paths are given by:

        "include" files:  $current_PGSINC
        toolkit:          $current_PGSTK
        hdf-eos(1):       $current_HDFEOS
        hdf-eos(5):       $current_HDFEOS5
        hdf(4):           $current_HDF
        hdf(5):           $current_HDF5
        gctp:             $current_GCTP

If any of these settings are wrong or blank, or you wish to change them in
order to prepare multiple installations at your site, you will be given an
opportunity to (re)set them momentarily.

EOF_3

 UserPrompt "Are all of these paths correct?[Y[es] or N[o][default]]"
   if [ "$user_response" != "" ] ; then
	case  "$user_response" in
	    n* | N* )
		change_paths="true"
	    ;;
	    y* | Y* )
		change_paths="false"
	    ;;
	esac
   else
	change_paths="false"
    fi

else
		change_paths="true"
fi

if [ $change_paths = "true" ] ; then
#Change Includes path
   eecchhoo "" "p g s i n c"
 UserPrompt "include files path (must be non-blank) [$current_PGSINC]"
   if [ "$user_response" != "" ] ; then
	 PGSINC=$user_response
   elif [ "$current_PGSINC" != "" ] ; then
	echo "include files path is still $current_PGSINC."
        PGSINC=$current_PGSINC
   else
	echo "Warning: No include files path selected; none found"
	echo "mls software may not compile properly "
	echo "unless you reconfigure; enter 'make configure'."
	PGSINC="/"
   fi

#Change Toolkit path
   eecchhoo "" "p g s t k"
 UserPrompt "Toolkit path (must be non-blank) [$current_PGSTK]"
   if [ "$user_response" != "" ] ; then
	 PGSTK=$user_response
   elif [ "$current_PGSTK" != "" ] ; then
	echo "Toolkit path is still $current_PGSTK."
        PGSTK=$current_PGSTK
   else
	echo "Warning: No toolkit path selected; none found"
	echo "mls software levels 1 and 3 may not link properly "
	echo "unless you reconfigure; enter 'make configure'."
	PGSTK="/"
   fi

#Change hdfeos(1) path
   eecchhoo "" "h d f e o s"
 UserPrompt "HDFEOS(1) path (must be non-blank) [$current_HDFEOS]"
   if [ "$user_response" != "" ] ; then
	 HDFEOS=$user_response
	 current_GCTP=$user_response
	 GCTP=$user_response
   elif [ "$current_HDFEOS" != "" ] ; then
	echo "hdfeos(1) path is still $current_HDFEOS."
        HDFEOS=$current_HDFEOS
   else
	echo "Warning: No HDFEOS(1) path selected; none found"
	echo "mls software may not link properly "
	echo "unless you reconfigure; enter 'make configure'."
	HDFEOS="/"
   fi

#Change hdfeos(5) path
   eecchhoo "" "h d f e o s 5"
 UserPrompt "HDFEOS(5) path (may be blank) [$current_HDFEOS5]"
   if [ "$user_response" = "<b>" ] ; then
	 HDFEOS5=""
	 echo "You will attempt build a mls software version without HDFEOS(5)"
   elif [ "$user_response" != "" ] ; then
	 HDFEOS5=$user_response
   elif [ "$current_HDFEOS5" != "" ] ; then
	echo "hdfeos(5) path is still $current_HDFEOS5."
        HDFEOS5=$current_HDFEOS5
   else
	echo "Warning: No HDFEOS(5) path selected; none found"
	echo "mls software may not link properly with newer Toolkit"
	echo "unless you reconfigure; enter 'make configure'."
	HDFEOS5="/"
   fi

#Change hdf(4) path
   eecchhoo "" "h d f"
 UserPrompt "HDF(4) path (must be non-blank) [$current_HDF]"
   if [ "$user_response" != "" ] ; then
	 HDF=$user_response
   elif [ "$current_HDF" != "" ] ; then
	echo "hdf(4) path is still $current_HDF."
        HDF=$current_HDF
   else
	echo "Warning: No HDF path selected; none found"
	echo "mls software may not link properly "
	echo "unless you reconfigure; enter 'make configure'."
	HDF="/"
   fi

#Change hdf(5) path
   eecchhoo "" "h d f 5"
 UserPrompt "HDF(5) path (may be blank) [$current_HDF5]"
   if [ "$user_response" = "<b>" ] ; then
	 HDF5=""
	 echo "You will attempt build a mls software version without HDF(5)"
   elif [ "$user_response" != "" ] ; then
	 HDF5=$user_response
   elif [ "$current_HDF5" != "" ] ; then
	echo "hdf(5) path is still $current_HDF5."
        HDF5=$current_HDF5
   else
	echo "Warning: No HDF(5) path selected; none found"
	echo "mls software may not link properly with newer Toolkit"
	echo "unless you reconfigure; enter 'make configure'."
	HDF5=""
   fi

#Change gctp path
   eecchhoo "" "g c t p"
 UserPrompt "GCTP path [$current_GCTP]"
   if [ "$user_response" != "" ] ; then
	 GCTP=$user_response
   elif [ "$current_GCTP" != "" ] ; then
	echo "GCTP path is still $current_GCTP."
        GCTP=$current_GCTP
   else
	echo "Warning: No GCTP path selected; none found"
	echo "mls software may not link properly "
	echo "unless you reconfigure; enter 'make configure'."
	GCTP="/"
   fi

else
    PGSINC=$current_PGSINC
    PGSTK=$current_PGSTK
    HDFEOS=$current_HDFEOS
    HDFEOS5=$current_HDFEOS5
    HDF=$current_HDF
    HDF5=$current_HDF5
    GCTP=$current_GCTP
fi
}

#------------------------------- GetPVM ------------
GetPVM()
{

which_blas "$current_BLAS" "$current_LIB_BLAS"
which_lapack "$current_LAPACK" "$current_LIB_LAPACK"

if [ "$add_PVM_PATH" != "true" ] ; then
	change_paths="false"
else
        more << EOF_4
                    *        *        *

The next questions refer to four special libraries: BLAS, LAPACK, PVM and FFTW.
Here too, it is possible that during the installation, these paths were
automatically "hard wired" as environment variables, and if so the values shown
below may be correct. If they are correct, simply answer Y[es] to the next
question. Otherwise you will be asked to supply the correct paths.

Currently these paths are given by:

        BLAS option    :  $which_blas_option
           meaning     :  $which_blas_msg
        LAPACK option  :  $which_lapack_option
           meaning     :  $which_lapack_msg
        PVM root       :  $current_PVM_ROOT
        FFTW path      :  $current_FFTW_ROOT

If these settings are wrong, or you wish to change them in order to prepare
multiple installations at your site, you will be given an opportunity to
(re)set them momentarily.

Note that if you wish to "unset" any, that is to give them blank values, you
cannot simply hit enter when asked to supply the new value because that means
"continue using the existing value" which is what you want only if the existing
value is already blank. Instead, to unset a non-blank existing value, enter
"<b>" (w/o the " marks).
EOF_4

 UserPrompt "Are these paths correct [Y[es][default] or N[o]]"
   if [ "$user_response" != "" ] ; then
	case  "$user_response" in
	    n* | N* )
		change_paths="true"
	    ;;
	    y* | Y* )
		change_paths="false"
	    ;;
	esac
   else
	change_paths="false"
    fi

fi

if [ $change_paths = "true" ] ; then

#BLAS options
   eecchhoo "" "b l a s"
   echo "The following options for satisfying BLAS routines are available"
   echo "(a) Use an externally-supplied library of BLAS routines"
   echo "(b) Use f95 intrinsics"
   echo "(c) Let the mls software build its own BLAS routines"
   echo "(Choose (a) only if you know your BLAS library path and name)"

   UserPrompt "Which of (a b c) do you choose [$which_blas_option]"
   case "$user_response" in
     a | A)
     #Change BLAS root path
     UserPrompt "BLAS root [$current_BLAS]"
     if [ "$user_response" = "<b>" ] ; then
	   BLAS=""
	   echo "You will rely upon internally-supplied BLAS"
     elif [ "$user_response" != "" ] ; then
	   BLAS=$user_response
     elif [ "$current_BLAS" != "" ] ; then
	   echo "BLAS root path is still $current_BLAS."
          BLAS=$current_BLAS
     else
	   echo "You will rely upon internally-supplied BLAS"
      echo "unless you reconfigure; enter 'make configure_pvm'."
      BLAS=""
     fi

     #Since we are using an external, don't let a prior choice of intrinsic stand
     if [ "$current_LIB_BLAS" = "f95" ] ; then
        current_LIB_BLAS=""
     fi                               

     #Change BLAS library name                                               
     UserPrompt "BLAS library name (if x, then libx.a) [$current_LIB_BLAS]"  
     if [ "$user_response" = "<b>" ] ; then                                  
      LIB_BLAS=""                                                            
      echo "BLAS library name is blas (default)"                             
     elif [ "$user_response" != "" ] ; then                                  
      LIB_BLAS=$user_response                                                
     elif [ "$current_LIB_BLAS" != "" ] ; then                               
      echo "BLAS lib name is still $current_LIB_BLAS."                        
          LIB_BLAS=$current_LIB_BLAS                                         
     else                                                                    
      echo "BLAS library name is blas (default)"                             
      LIB_BLAS=""                                                            
     fi                                                                      
         ;;
     b | B)
      echo "Using f95 intrinsics to satisfy BLAS routines"                             
	   BLAS=""
      LIB_BLAS="f95"                                                            
         ;;

     # c | C)
     *)
      echo "Let the mls software build its own BLAS routines"                             
	   BLAS=""
      LIB_BLAS=""                                                            
         ;;

   esac
   
#LAPACK options
   eecchhoo "" "l a p a c k"
   echo "The following options for satisfying LAPACK routines are available"
   echo "(a) Use an externally-supplied library of LAPACK routines"
   echo "(b) Use f95 intrinsics"
   echo "(Choose (a) only if you know your LAPACK library path and name)"

   UserPrompt "Which of (a b) do you choose [$which_lapack_option]"
   case "$user_response" in
     a | A)
     #Change LAPACK root path
     UserPrompt "LAPACK root [$current_LAPACK]"
     if [ "$user_response" = "<b>" ] ; then
	   LAPACK=""
	   echo "You will rely upon f95 intrinsics for LAPACK"
     elif [ "$user_response" != "" ] ; then
	   LAPACK=$user_response
     elif [ "$current_LAPACK" != "" ] ; then
	   echo "LAPACK root path is still $current_LAPACK."
          LAPACK=$current_LAPACK
     else
	   echo "You will rely upon f95 intrinsics for LAPACK"
      echo "unless you reconfigure; enter 'make configure_pvm'."
      LAPACK=""
     fi

     #Since we are using an external, don't let a prior choice of intrinsic stand
     if [ "$current_LIB_LAPACK" = "f95" ] ; then
        current_LIB_LAPACK=""
     fi                               

     #Change LAPACK library name                                               
	  echo "(Enter multiple names on the same line like this: x y z)"
     UserPrompt "LAPACK library names (if x, then libx.a) [$current_LIB_LAPACK]"  
     if [ "$user_response" = "<b>" ] ; then                                  
      LIB_LAPACK=""                                                            
      echo "LAPACK library name is lapack (default)"                             
     elif [ "$user_response" != "" ] ; then                                  
      LIB_LAPACK=$user_response                                                
     elif [ "$current_LIB_LAPACK" != "" ] ; then                               
      echo "LAPACK lib name is still $current_LIB_LAPACK."                        
          LIB_LAPACK=$current_LIB_LAPACK                                         
     else                                                                    
      echo "LAPACK library name is lapack (default)"                             
      LIB_LAPACK=""                                                            
     fi                                                                      
         ;;
     # b | B)
     *)
      echo "Using f95 intrinsics to satisfy LAPACK routines"                             
	   LAPACK=""
      LIB_LAPACK="f95"                                                            
         ;;

   esac
   
#Change PVM root path
   eecchhoo "" "p v m"
 UserPrompt "PVM root (enter <b> to force back to blank) [$current_PVM_ROOT]"
   if [ "$user_response" = "<b>" ] ; then
	 PVM_ROOT=""
	 echo "You will build a mls software version without PVM support"
   elif [ "$user_response" != "" ] ; then
	 PVM_ROOT=$user_response
   elif [ "$current_PVM_ROOT" != "" ] ; then
	echo "PVM root path is still $current_PVM_ROOT."
        PVM_ROOT=$current_PVM_ROOT
   else
	echo "Warning: No PVM ROOT path selected; none found"
	echo "You will build a mls software version without PVM support"
	echo "unless you reconfigure; enter 'make configure_pvm'."
	PVM_ROOT=""
   fi

#Change FFTW root path
   eecchhoo "" "f f t w"
 UserPrompt "FFTW root (enter <b> to force back to blank) [$current_FFTW_ROOT]"
   if [ "$user_response" = "<b>" ] ; then
	 FFTW_ROOT=""
	 echo "You will build a mls software version without FFTW support"
   elif [ "$user_response" != "" ] ; then
	 FFTW_ROOT=$user_response
   elif [ "$current_FFTW_ROOT" != "" ] ; then
	echo "FFTW path is still $current_FFTW_ROOT."
        FFTW_ROOT=$current_FFTW_ROOT
   else
	echo "Warning: No FFTW root path selected; none found"
	echo "The level 3 mls software will not link properly"
	echo "unless you reconfigure; enter 'make configure_pvm'."
	FFTW_ROOT=""
   fi

else
    BLAS=$current_BLAS
    LIB_BLAS=$current_LIB_BLAS
    LAPACK=$current_LAPACK
    LIB_LAPACK=$current_LIB_LAPACK
    PVM_ROOT=$current_PVM_ROOT
#    PVM_ARCH=$current_PVM_ARCH
    FFTW_ROOT=$current_FFTW_ROOT
fi

#PVM arch is based on platform
#platform        PVM_ARCH
#  Sun           SUN4SOL2
#  SGI            SGI6
#  Linux         LINUX
#  None          LINUX

if [ "$platform" = "Sun" ] ; then
	PVM_ARCH="SUN4SOL2"
elif [ "$platform" = "SGI" ] ; then
	PVM_ARCH="SGI6"
else
	PVM_ARCH="LINUX"
fi
}

#------------------------------- GetFOPTS ------------

GetFOPTS()
{
        more << EOF_5
                    *        *        *

You may change the current options passed to the compiler and linker. Normally
the default options work well, but you may wish to set debugging, turn on
warning messages, or choose advanced optimizations. Consult your manual for
the precise format before changing these. 

To reset an option to its default enter the word "default" (w/o the " marks)
at the prompt.

EOF_5

#accept user compiler/linker options to be written to file .configure

   eecchhoo "" "F O P T S"
 UserPrompt "Fortran 95 Compiler options [$current_FOPTS]"
   if [ "$user_response" = "default" ] ; then
		current_FOPTS=
   elif [ "$user_response" != "" ] ; then
		current_FOPTS="$user_response"
	fi

   eecchhoo "" "L D O P T S"
 UserPrompt "Fortran 95 Linker options [$current_LDOPTS]"
   if [ "$user_response" = "default" ] ; then
		current_LDOPTS=
   elif [ "$user_response" != "" ] ; then
		current_LDOPTS="$user_response"
	fi

}

#------------------------------- Help ------------
#
# Function to output brief help message and exit
#

HelpBrief()
{

        more << EOF_6
                    *        *        *

In order to properly build the mls software, a configuration step is required.
Normally this is done only once: immediately after un-tarring or copying the
source onto your machine. However in case of trouble, to optimize speed, or for
other reasons this may need to be done again.

The configuration step can be subdivided into three sub-steps: the first is
basic and an absolute prerequisite; the other two are optional
(i)    Identify your compiler, platform type, and paths to installed libraries
       of HDF, HDFEOS, and Toolkits. This is the most basic info and you will
       automatically be prompted for it. To change these settings later,
       enter "make configure"
(ii)   Decide if you want to build the software with support for external BLAS,
       LAPACK, PVM and FFTW. The first three may improve performance, while the
       last is needed to build level 3. These require setting paths to installed
       libraries. To learn where to obtain them, enter "BEFORE.mls". To 
       change these settings later, enter "make configure_pvm"
(iii)  Choose compiler and linker options. Although these are automatically
       set to default values that work well, you may have a reason to prefer
       different options.To change these settings later,
       enter "make configure_fopts"
       
EOF_6

#No further help available yet
    exit
}

#------------------------------- Help ------------
#
# Function to output help options and exit
#

Help()
{

        more << EOF_7
To see help on specific topics:
Topic                            Command
Makefile scripts                 'make help--scripts'
Makefiles                        'make help--Makefile'
Prerequisites                    'make firsthelp'
In depth explanation             'make disthelp'
Brief overview                   'make help--brief'
EOF_7

#No further help available yet
    exit
}

#---------------------------- lhs_eq_rhs
#
# Function to assign second arg to first: lhs=rhs
# where (lhs rhs) = ($1 $2)
# if given optional third arg "n"
# assigns $$..$lhs = $$..$rhs

lhs_eq_rhs()
{

   # Do we have write permission in ./?
      if [ ! -w "./" ]
      then
         echo "Sorry--need write permission in ./ to operate"
         exit 1
      fi
      
      rm -f temp.lhs_eq_rhs
      if [ $# -lt 3 ]
      then
         echo "$1=$2" > temp.lhs_eq_rhs
         . temp.lhs_eq_rhs
      else
         mega_buck $3 $1
         lhs=$mega_buck_result
         mega_buck $3 $2
         rhs=$mega_buck_result
         echo "$lhs=$rhs" > temp.lhs_eq_rhs
         . temp.lhs_eq_rhs
      fi
      rm -f temp.lhs_eq_rhs
}
      
#------------------------------- Main Program ------------

#****************************************************************
#                                                               *
#                  * * * Main Program  * * *                    *
#                                                               *
#                                                               *
#	The entry point where control is given to the script         *
#****************************************************************

# Set the following to "on" to print degugging info
debugging="off"

#Default compiler and linker options
MLS_default_FOPTS_NAG="-w"
MLS_default_FOPTS_NAG_SGI="-w -abi=n32"
MLS_default_FOPTS_LF95=
MLS_default_FOPTS_Abs="-w"
MLS_default_LDOPTS=

#---------------------- variables controlling mlsconfigure
#                        controllable by Options--see above

#conf_dir     the directory where the .configure file is to be stored
#plat_dir     the directory to keep the platforms subdirectories
#get_confg    true if need to query for configuration; false if use input values
#write_confg  true if need to (re)write .configure file
#chngd_confg  true if user changed MLSF95 or MLSPLAT; else false
#add_PVM_PATH true if need to query for PVM and FFTW paths; else false
#add_FOPTS    true if need to query for FOPTS and LDOPTS; else false
#del_exist_dir  
#             true if need to delete existing uniquely-named sub-dir
#made_new_dir true if created new uniquely-named sub-dir; else false

#---------------------- Settings written to .configure file

#MLSF95     name of the compiler: LF95, NAG, Sun, Abs
#MLSPLAT    name of the platform: Sun, SGI, or Linux
#MLSCONFG   MLSF95.MLSPLAT or else a name chosen by user
#PGSINC     path to the toolbox include files
#PGSTK      path to the toolbox library libPGSTK.a
#           if blank, then build w/o toolkit
#HDFEOS     path to the hdfeos(1) library libhdfeos.a
#HDFEOS5    path to the hdfeos(5) library libhe5_hdfeos.a
#HDF        path to the hdf(4) library libmfhdf.a, etc.
#HDF5       path to the hdf(5) library libhdf5_fortran.a, etc.
#GCTP       path to the gctp library libGctp.a
#PGSLIB     PGSTK (duplicate)
#HDFEOS_LIB HDFEOS (duplicate)
#HDFLIB     HDF (duplicate)
#BLAS       if non-blank, root of path to the blas library BLAS/libblas.a,
#           if blank, then use internally supplied library
#LIB_BLAS   name x of the blas library BLAS/libx.a,
#           if blank, then x of libx.a
#LAPACK     if non-blank, root of path to the blas library LAPACK/liblapack.a,
#           if blank, then use internally supplied library
#LIB_LAPACK   name x of the blas library LAPACK/libx.a,
#           if blank, then x of libx.a
#PVM_ROOT   root of path to the pvm library lib/PVM_ARCH/libpvm3.a, etc.
#PVM_ARCH   OS & platform type: LINUX, SGI6, SGI64, SUN4SOL2
#FFTW_ROOT  path to the fftw library libfftw.a, etc.
#FOPTS      options used in all .o build commands (except the custom ones)
#LDOPTS     options used in all executable build commands

#---------------------- Name given to .configure file

#MLSCFILE     name of the .configure file; defaults to .configure

#---------------------- 

# List all settings (some are duplicates--see above)
# Add any additional ones to this sh array
# Be aware then of possibly needing to add current* settings below
# Also, decide where to actually interactively read user input
# e.g., GetPVM, GetFOPTS or GetPlatform
all_my_opts="MLSF95 MLSPLAT MLSCONFG PGSINC PGSTK HDFEOS HDFEOS5 \
HDF HDF5 GCTP PGSLIB HDFEOS_LIB HDFLIB BLAS LIB_BLAS LAPACK LIB_LAPACK \
PVM_ROOT PVM_ARCH FFTW_ROOT FOPTS LDOPTS"

MLSCFILE=.configure

conf_dir="./"
plat_dir="./"
mcfg_dir="./"
get_confg="true"
del_exist_dir="true"
chngd_confg="false"

# These three stand out as poorly chosen--
# They violate the pattern current_VARIABLE=$VARIABLE
# which could itself be automated to loop over all_my_opts
# and thus be shorter and easier to extend with something like
#   for path in $all_my_opts
#     lhs_eq_rhs current_${path} $path 2
#   do
#   done
# We'll try this out in a future version of mlsconfigure
# in which we make the replacements
# current_compiler -> current_MLSF95
# current_platform -> current_MLSPLAT
# current_confg -> current_MLSCONFG
current_compiler=$MLSF95
current_platform=$MLSPLAT
current_confg=$MLSCONFG

current_PGSINC=$PGSINC
current_PGSTK=$PGSLIB
current_HDFEOS=$HDFEOS_LIB
current_HDF=$HDFLIB
current_GCTP=$HDFEOS_LIB
current_HDF5=$HDF5
current_HDFEOS5=$HDFEOS5

# Whether to include PVM & FFTW paths in .configure
add_PVM_PATH="false"
current_BLAS=$BLAS
current_LIB_BLAS=$LIB_BLAS
current_LAPACK=$LAPACK
current_LIB_LAPACK=$LIB_LAPACK
current_PVM_ROOT=$PVM_ROOT
current_PVM_ARCH=$PVM_ARCH
current_FFTW_ROOT=$FFTW_ROOT

# Whether to include default FOPTS and LDOPTS in .configure
add_FOPTS="false"
current_FOPTS=$FOPTS
current_LDOPTS=$LDOPTS

# Debugging--reveal starting values
if [ "$debugging" = "on" ] ; then
   for path in $all_my_opts
   do
      mega_buck 1 $path
      echo "$path=$mega_buck_result"
   done
	echo "add_PVM_PATH=$add_PVM_PATH"
	echo "MLSCFILE=$MLSCFILE"
fi

#
# Get arguments from command line
#

me="$0"
me_simple=mlsconfigure
REECHO="`echo $0 | sed 's/mlsconfigure/reecho.sh/'`"

while [ "$1" != "" ] ; do

    case "$1" in

	-h | -help )
	    Help
       exit
	;;

	-help--brief )
	    HelpBrief
       exit
	;;

	-help--mlsconfigure )
	    sed -n '/'$me_simple' help/,/End '$me_simple' help/ p' $me \
		| sed -n 's/^..//p' | sed '1 d; $ d'
       exit
	;;

	-c )
	    current_compiler=$2
	    shift
	;;

	-confg )
	    current_confg=$2
	    shift
	;;

	-p )
	    current_platform=$2
	    shift
	;;

	-dc )
	    conf_dir=$2
	    shift
	;;

	-pc )
	    plat_dir=$2
	    shift
	;;

	-mc )
	    mcfg_dir=$2
	    shift
	;;

	-cf )
	    MLSCFILE=$2
	    shift
	;;

	-nc )
	    get_confg="false"
	;;

	-nd )
	    del_exist_dir="false"
	;;

	-pv )
	    add_PVM_PATH="true"
	;;

	-fl )
	    add_FOPTS="true"
	;;

	* )
       echo "Unrecognized option in util/mlsconfigure: $1"
	    Help
       exit
	;;

    esac
    shift

done

if [ "$debugging" = "on" ] ; then
	echo "get_confg=$get_confg"
	echo "MLSCFILE=$MLSCFILE"
	echo "add_FOPTS=$add_FOPTS"
	echo "add_PVM_PATH=$add_PVM_PATH"
fi

write_confg="false"

if [ $get_confg = "true" ] ; then
   if [ "$debugging" = "on" ] ; then
      echo "Calling GetPlatform"
   fi
	GetPlatform
	write_confg="true"
else
        compiler=$current_compiler
        platform=$current_platform
fi

#If user changed the compiler or platform, automatically query
#for new pvm path, etc. and FOPTS, etc.
#also blank out existing settings for FOPTS and LDOPTS
if [ $chngd_confg = "true" ] ; then
	add_PVM_PATH="true"
	add_FOPTS="true"
	current_FOPTS=""
	current_LDOPTS=""
fi

if [ $add_PVM_PATH = "true" ] ; then
   if [ "$debugging" = "on" ] ; then
      echo "Calling GetPVM"
   fi
	GetPVM
	write_confg="true"
fi

if [ $add_FOPTS = "true" ] ; then
   if [ "$debugging" = "on" ] ; then
      echo "Calling GetFOPTS"
   fi
	GetFOPTS
	write_confg="true"
fi

if [ "$current_FOPTS" = "" ] ; then
		if [ "$compiler" = "NAG" ] ; then
			if [ "$platform" = "SGI" ] ; then
				FOPTS="$MLS_default_FOPTS_NAG_SGI"
			else
				FOPTS="$MLS_default_FOPTS_NAG"
			fi
		elif [ "$compiler" = "Abs" ] ; then
			FOPTS="$MLS_default_FOPTS_Abs"
		elif [ "$compiler" = "Sun" ] ; then
			FOPTS="$MLS_default_FOPTS_Abs"
		else
			FOPTS="$MLS_default_FOPTS_LF95"
		fi
else
	FOPTS=$current_FOPTS
fi

if [ "$current_LDOPTS" = "" ] ; then
			LDOPTS="$MLS_default_LDOPTS"
else
	LDOPTS=$current_LDOPTS
fi

if [ $write_confg = "true" ] ; then
# 1st--check on blank paths
# if blank, attempt alternate settings
# if that fails, echo regrets and abort
	if [ "$PGSTK" = "" ] ; then
		PGSTK=$PGSLIB
	fi
	if [ "$PGSTK" = "" ] ; then
		echo " Warning--the toolkit path is blank--only level 2 may be built"
	fi
	
	if [ "$HDF" = "" ] ; then
		HDF=$HDFLIB
	fi
	if [ "$HDF" = "" ] ; then
		echo " Sorry--the HDF path must not be blank"
		exit
	fi
	
	if [ "$HDFEOS" = "" ] ; then
		HDFEOS=$HDFEOS_LIB
	fi
	if [ "$HDFEOS" = "" ] ; then
		echo " Sorry--the HDFEOS path must not be blank"
		exit
	fi
	
	if [ "$GCTP" = "" ] ; then
		GCTP=$HDFEOS_LIB
	fi
	if [ "$GCTP" = "" ] ; then
		echo " Sorry--the GCTP path must not be blank"
		exit
	fi
	
#	Create .configure file
	if [ -f $conf_dir/$MLSCFILE ] ; then
		chmod u+w $conf_dir/$MLSCFILE
		rm -f $conf_dir/$MLSCFILE
      confg_is="changed"
   else
      confg_is="new"
	fi

#	Because MakeFC checks on whether MLSCONFG is empty, not whether it is "."
#	MLSCONFG=$compiler.$platform
	if [ "MLSCONFG" = "." ] ; then
		MLSCONFG=
	fi
	
	echo "#	.configure for mls" > $conf_dir/$MLSCFILE
   # duplicate some settings (shouldn't you find a cleaner fix?)
   MLSF95=$compiler
   MLSPLAT=$platform
#   MLSCONFG=$compiler.$platform
   PGSLIB=$PGSTK
   HDFEOS_LIB=$HDFEOS
   HDFLIB=$HDF
   for path in $all_my_opts
   do
      mega_buck 1 $path
      echo "$path=$mega_buck_result" >> $conf_dir/$MLSCFILE
   done
   for path in $all_my_opts
   do
      echo "export $path" >> $conf_dir/$MLSCFILE
   done
else
#	just re-use current settings
	compiler=$current_compiler
	platform=$current_platform
   MLSF95=$compiler
   MLSPLAT=$platform
#   MLSCONFG=$compiler.$platform
   confg_is="the_same"
fi

export MLSF95
export MLSPLAT
export MLSCONFG

if [ $get_confg = "true" -o $add_PVM_PATH = "true" -o $add_FOPTS = "true" ]
then
   for path in $all_my_opts
   do
      mega_buck 1 $path
	   echo "$path is now $mega_buck_result"
   done
fi

#  Warn of massive recompilation after changes to .configure file
if [ "$confg_is" = "changed" ] ; then                                 
   echo "   N o t i c e"                                              
   echo "You have changed your .configure file: $conf_dir/$MLSCFILE"  
   echo "(The next make command may trigger massive recompilation"    
   echo "unless you do a 'make update' first or set NOCLEANING)"      
fi                                                                    

#Don't create object-file directory if platforms not a directory
if [ ! -d $plat_dir/platforms ] ; then
	exit
fi

#Re-create object-file directory for this MLSCONFG
#unless $del_exist_dir reset to false
#(Because mlsconfigure may be called simply to update $MLSCONFG/Makefile)
made_new_dir="false"

if [ "$MLSCONFG" = "." -o "$MLSCONFG" = "" ] ; then
	echo "MLSCONFG not yet defined--still $MLSCONFG"
	echo "To repair this, enter 'make configure'"
   exit
elif [ "$del_exist_dir" != "true" ] ; then
	if [ ! -d $mcfg_dir/$MLSCONFG ] ; then
      mkdir $mcfg_dir/$MLSCONFG
		made_new_dir="true"
   else
      rm -f $mcfg_dir/$MLSCONFG/Makefile
	fi
elif [ -d $mcfg_dir/$MLSCONFG ] ; then
#	echo "Clearing out directory `pwd`$mcfg_dir/$MLSCONFG"
#	echo "(Be careful that this is not too ambitious)"
	chmod u+w $mcfg_dir/$MLSCONFG/*
#	rm -f $mcfg_dir/$MLSCONFG/*.o
#	rm -f $mcfg_dir/$MLSCONFG/*.mod
#	rm -f $mcfg_dir/$MLSCONFG/Makefile
	rm -f $mcfg_dir/$MLSCONFG/*
else
   mkdir $mcfg_dir/$MLSCONFG   
	made_new_dir="true"        
fi

if [ ! -f $plat_dir/platforms/$MLSF95.$MLSPLAT ] ; then
	echo "File $MLSF95.$MLSPLAT not found in $plat_dir/platforms"
	exit
fi

if [ ! -f $plat_dir/platforms/targets ] ; then
	echo "File targets not found in $plat_dir/platforms"
	exit
fi

cat $conf_dir/$MLSCFILE $plat_dir/platforms/$MLSF95.$MLSPLAT \
   $plat_dir/platforms/targets > $mcfg_dir/$MLSCONFG/Makefile

if [ "$made_new_dir" = "true" ] ; then
	echo "Configured mls to use $mcfg_dir/$MLSCONFG "
	echo "(This is where your object files, .mod files, libraries,"
	echo "and executable programs will be created)"
	echo "To build the software, enter the 'make' command again"
	echo ""
	echo "If you later wish to rebuild for a different compiler"
	echo "or platform, enter 'make configure'"
   if [ "$MLSCONFG" != "$MLSF95.$MLSPLAT" ] ; then
     # Custom configuration name -- create a machines sub-directory for it
     # We will assume that the machines sub-directories live under the path
     # $conf_dir/lib/machines/$MLSCONFG
     machines_root=$conf_dir/lib/machines
     if [ ! -d "$machines_root" ] ; then
        echo "Unable to locate root machines directory $machines_root"
        exit
     fi
     machines_base=$machines_root/$MLSF95.$MLSPLAT
     if [ ! -d "$machines_base" ] ; then
        echo "Unable to locate base machines directory $machines_base"
        exit
     fi
     if [ ! -d "$machines_root/$MLSCONFG" ] ; then
        mkdir "$machines_root/$MLSCONFG"
        cp $machines_base/*.f9* $machines_root/$MLSCONFG
        echo "New directory $machines_root/$MLSCONFG based on $machines_base"
     fi
   fi
fi

exit
# $Log$
# Revision 1.26  2001/11/09 21:49:39  pwagner
# User-defined configuration names possible
#
# Revision 1.25  2001/11/08 00:39:14  pwagner
# New help system; mention of NOCLEANING where appropriate
#
# Revision 1.24  2001/11/07 00:27:49  pwagner
# Tells how to enter multiple LAPACK library names
#
# Revision 1.23  2001/11/06 00:20:34  pwagner
# Sets BLAS, LAPACK options and paths in new, simpler way
#
# Revision 1.22  2001/10/10 23:23:54  pwagner
# New parameter allows use of single platforms directory by > 1 (MLSCONFG)
#
# Revision 1.21  2001/09/04 23:33:35  pwagner
# Added Sun's own f95 option for MLSF95
#
# Revision 1.20  2001/08/15 20:57:26  pwagner
# Fixed bug--MLSF95 vand MLSPLAT were undefined
#
# Revision 1.19  2001/07/27 19:57:07  pwagner
# Added mega_buck function; exports BLAS and LIB_BLAS
#
# Revision 1.18  2001/07/12 22:39:24  pwagner
# Now exports HDFEOS5
#
# Revision 1.17  2001/06/29 23:58:39  pwagner
# Added LIB_BLAS and HDFEOS5
#
# Revision 1.16  2001/06/11 20:52:41  pwagner
# Fixed tiny error in blank assignment of HDF5
#
# Revision 1.15  2001/06/01 20:30:07  pwagner
# New print statements if debugging on
#
# Revision 1.14  2001/05/31 23:25:02  pwagner
# Slightly more consistent messages
#
# Revision 1.13  2001/05/31 21:55:02  pwagner
# Now includes HDF5 in .configure
#
# Revision 1.12  2001/05/14 17:37:14  pwagner
# .configure now a variable file name
#
# Revision 1.11  2001/03/23 00:40:42  pwagner
# Better message if pvm, fftw not set
#
# Revision 1.10  2001/03/16 18:53:28  pwagner
# Resets FOPTS, LDOPTS if chngd_config; also automatically full queries
#
# Revision 1.9  2001/03/06 00:16:14  pwagner
# Added Absoft compiler
#
# Revision 1.8  2001/02/27 18:10:44  pwagner
# exports FOPTS and LDOPTS; better Help
#
# Revision 1.7  2001/02/26 18:39:15  pwagner
# Fixed problem with older .configure files
#
# Revision 1.6  2001/02/26 00:26:49  pwagner
# default FOPTS and LDOPTS can be set,  saved to .configure
#
# Revision 1.5  2001/02/10 00:06:47  pwagner
# update now a target of make -f MakeFC; replaces customized Makefiles with latest versions
#
# Revision 1.4  2001/01/23 19:41:36  pwagner
# Adds support for PVM
#
# Revision 1.3  2000/10/21 00:23:58  pwagner
# Added paths to .configure
#
# Revision 1.2  2000/10/18 20:56:21  pwagner
# Fixed obvious bug; 1st step towards -h option
#
# Revision 1.1  2000/10/16 18:31:19  pwagner
# first commit
#

