#!/bin/csh

# This shell script takes the names of Fortran 77 files and creates
# Fortran 90 modules corresponding to them, by using the end_stmts program
# to change plain END statements to END SUBROUTINE or END FUNCTION statements.

foreach f ($*)
      set b=`basename $f .f`
      echo "      MODULE" $b"_m"         >$b"_m".f
      echo "      CONTAINS"             >>$b"_m".f
      end_stmts <$f                     >>$b"_m".f
      echo "      END MODULE" $b"_m"    >>$b"_m".f
end
