#Makefile.dep -- a file to be included by a Makefile
#to compile a Fortran 9x program or library
OBJS = \
Allocate_Deallocate.o  		dates_module.o  \
Geometry.o  			declaration_table.o  \
GriddedData.o  			dump_0.o  \
HDF-EOS.o  			error_handler.o  \
Hdf.o  				expr_m.o  \
Init_MLSSignals_m.o  		hash.o  \
L1BData.o  			heights_module.o  \
L2GPData.o  			intrinsic.o  \
L2PC_m.o  			io_stuff.o  \
MLSCF.o  			l3ascii.o  \
MLSCommon.o  			lexer_core.o  \
MLSFiles.o  			lexer_m.o  \
MLSMessageModule.o  		ncep_dao.o  \
MLSNumerics.o  			output_m.o  \
MLSPCF.o  			parser.o  \
MLSSignalNomenclature.o  	string_table.o  \
MLSSignals_m.o  		swapi.o  \
MLSStrings.o  			swapi_character_array.o  \
ManipulateVectorQuantities.o  	swapi_character_scalar.o  \
MatrixModule_0.o  		swapi_double.o  \
MatrixModule_1.o  		swapi_integer.o  \
Molecules.o  			swapi_real.o  \
MoreTree.o  			symbol_table.o  \
PCFHdr.o  			symbol_types.o  \
PVM.o  				table_dumper.o  \
PVMIDL.o  			table_generator.o  \
Parse_Signal_m.o  		toggles_core.o  \
QuantityTemplates.o  		trace_m.o  \
SDPToolkit.o  			tree.o  \
SDPToolkitSubstitute.o  	tree_types.o  \
VGridsDatabase.o  		units.o  \
VectorsModule.o  \
 
# using f90makedep.pl to calculate dependencies 
Allocate_Deallocate.o: Allocate_Deallocate.f90 MLSCommon.o MLSMessageModule.o
Geometry.o: Geometry.f90 MLSCommon.o
GriddedData.o: GriddedData.f90 MLSCommon.o
Hdf.o: Hdf.f90 MLSCommon.o
Init_MLSSignals_m.o: Init_MLSSignals_m.f90 Molecules.o intrinsic.o tree.o \
	tree_types.o make_tree.f9h
L1BData.o: L1BData.f90 MLSCommon.o MLSMessageModule.o
L2GPData.o: L2GPData.f90 Allocate_Deallocate.o HDF-EOS.o Hdf.o MLSCommon.o \
	MLSMessageModule.o dump_0.o output_m.o string_table.o swapi.o \
	addItemToDatabase.f9h
L2PC_m.o: L2PC_m.f90 MLSCommon.o MLSMessageModule.o MLSSignals_m.o \
	MatrixModule_0.o MatrixModule_1.o QuantityTemplates.o VectorsModule.o \
	intrinsic.o string_table.o addItemToDatabase.f9h
MLSFiles.o: MLSFiles.f90 HDF-EOS.o MLSCommon.o MLSStrings.o SDPToolkit.o \
	output_m.o
MLSMessageModule.o: MLSMessageModule.f90 SDPToolkit.o
MLSNumerics.o: MLSNumerics.f90 Allocate_Deallocate.o MLSCommon.o \
	MLSMessageModule.o MLSStrings.o MatrixModule_0.o
MLSSignalNomenclature.o: MLSSignalNomenclature.f90 MLSCommon.o \
	MLSMessageModule.o MLSStrings.o intrinsic.o
MLSSignals_m.o: MLSSignals_m.f90 Allocate_Deallocate.o Init_MLSSignals_m.o \
	MLSCommon.o MLSMessageModule.o MoreTree.o dump_0.o expr_m.o \
	intrinsic.o lexer_core.o output_m.o string_table.o toggles_core.o \
	trace_m.o tree.o tree_types.o addItemToDatabase.f9h
MLSStrings.o: MLSStrings.f90 MLSCommon.o MLSMessageModule.o
ManipulateVectorQuantities.o: ManipulateVectorQuantities.f90 MLSCommon.o \
	MLSMessageModule.o MLSNumerics.o VectorsModule.o
MatrixModule_0.o: MatrixModule_0.f90 Allocate_Deallocate.o MLSCommon.o \
	MLSMessageModule.o dump_0.o output_m.o
MatrixModule_1.o: MatrixModule_1.f90 Allocate_Deallocate.o MLSCommon.o \
	MLSMessageModule.o MatrixModule_0.o VectorsModule.o dump_0.o \
	output_m.o string_table.o addItemToDatabase.f9h
Molecules.o: Molecules.f90 intrinsic.o tree.o tree_types.o make_tree.f9h
MoreTree.o: MoreTree.f90 intrinsic.o tree.o tree_types.o
PCFHdr.o: PCFHdr.f90 Hdf.o MLSCommon.o MLSMessageModule.o SDPToolkit.o
PVM.o: PVM.f90 MLSCommon.o
PVMIDL.o: PVMIDL.f90 MLSCommon.o PVM.o
Parse_Signal_m.o: Parse_Signal_m.f90 Allocate_Deallocate.o \
	Init_MLSSignals_m.o MLSSignals_m.o MoreTree.o declaration_table.o \
	intrinsic.o lexer_core.o lexer_m.o output_m.o string_table.o \
	symbol_table.o symbol_types.o tree.o
QuantityTemplates.o: QuantityTemplates.f90 Allocate_Deallocate.o MLSCommon.o \
	MLSMessageModule.o intrinsic.o output_m.o addItemToDatabase.f9h
SDPToolkit.o: SDPToolkit.f90 MLSCommon.o PGS_CBP.f PGS_CBP_6.f PGS_CSC_4.f \
	PGS_EPH_5.f PGS_IO.f PGS_IO_1.f PGS_MEM_7.f PGS_MET.f PGS_MET_13.f \
	PGS_PC.f PGS_PC_9.f PGS_SMF.f PGS_TD.f PGS_TD_3.f
VGridsDatabase.o: VGridsDatabase.f90 Allocate_Deallocate.o MLSCommon.o \
	MLSMessageModule.o dump_0.o intrinsic.o output_m.o string_table.o \
	addItemToDatabase.f9h
VectorsModule.o: VectorsModule.f90 Allocate_Deallocate.o MLSCommon.o \
	MLSMessageModule.o QuantityTemplates.o dump_0.o output_m.o \
	string_table.o addItemToDatabase.f9h
dates_module.o: dates_module.f90 MLSMessageModule.o MLSStrings.o
declaration_table.o: declaration_table.f90 intrinsic.o output_m.o \
	string_table.o toggles_core.o
dump_0.o: dump_0.f90 output_m.o
error_handler.o: error_handler.f90 output_m.o
expr_m.o: expr_m.f90 declaration_table.o intrinsic.o string_table.o \
	toggles_core.o trace_m.o tree.o tree_types.o
heights_module.o: heights_module.f90 MLSCommon.o MLSMessageModule.o
intrinsic.o: intrinsic.f90 Allocate_Deallocate.o symbol_table.o \
	symbol_types.o tree.o tree_types.o make_tree.f9h
l3ascii.o: l3ascii.f90 GriddedData.o MLSCommon.o MLSStrings.o dates_module.o \
	lexer_core.o output_m.o tree.o
lexer_core.o: lexer_core.f90 output_m.o string_table.o symbol_table.o \
	toggles_core.o
lexer_m.o: lexer_m.f90 error_handler.o lexer_core.o output_m.o string_table.o \
	symbol_table.o symbol_types.o toggles_core.o
ncep_dao.o: ncep_dao.f90 GriddedData.o HDF-EOS.o Hdf.o MLSCommon.o MLSFiles.o \
	MLSMessageModule.o MLSStrings.o SDPToolkit.o dump_0.o l3ascii.o \
	lexer_core.o output_m.o tree.o addItemToDatabase.f9h
output_m.o: output_m.f90 MLSMessageModule.o
parser.o: parser.f90 lexer_core.o lexer_m.o output_m.o symbol_table.o \
	symbol_types.o toggles_core.o tree.o tree_types.o
string_table.o: string_table.f90 hash.o io_stuff.o output_m.o
swapi.o: swapi.f90 swapi_character_array.o swapi_character_scalar.o \
	swapi_double.o swapi_integer.o swapi_real.o
symbol_table.o: symbol_table.f90 output_m.o string_table.o symbol_types.o \
	toggles_core.o
symbol_types.o: symbol_types.f90 string_table.o
table_dumper.o: table_dumper.f90 MLSCF.o declaration_table.o intrinsic.o \
	output_m.o string_table.o
table_generator.o: table_generator.f90 MLSCF.o declaration_table.o expr_m.o \
	intrinsic.o lexer_core.o output_m.o string_table.o toggles_core.o \
	trace_m.o tree.o tree_types.o
trace_m.o: trace_m.f90 lexer_core.o output_m.o tree.o
tree.o: tree.f90 error_handler.o output_m.o string_table.o symbol_table.o \
	symbol_types.o toggles_core.o tree_types.o
tree_types.o: tree_types.f90 string_table.o symbol_types.o
units.o: units.f90 MLSCommon.o declaration_table.o intrinsic.o tree.o
 
#End of Makefile.dep
 
