#Makefile.dep -- a file to be included by a Makefile
#to compile a Fortran 9x program or library
OBJS = \
Allocate_Deallocate.o  		expr_m.o  \
GriddedData.o  			hash.o  \
HDF-EOS.o  			heights_module.o  \
Hdf.o  				intrinsic.o  \
L1BData.o  			io_stuff.o  \
L2GPData.o  			lexer_core.o  \
MLSCF.o  			lexer_m.o  \
MLSCommon.o  			output_m.o  \
MLSMessageModule.o  		parser.o  \
MLSNumerics.o  			string_table.o  \
MLSPCF.o  			swapi.o  \
MLSSignalNomenclature.o  	swapi_character_array.o  \
MLSStrings.o  			swapi_character_scalar.o  \
ManipulateVectorQuantities.o  	swapi_double.o  \
MatrixModule_0.o  		swapi_integer.o  \
MatrixModule_1.o  		swapi_real.o  \
Molecules.o  			symbol_table.o  \
MoreTree.o  			symbol_types.o  \
QuantityTemplates.o  		table_dumper.o  \
SDPToolkit.o  			table_generator.o  \
SDPToolkitSubstitute.o  	toggles_core.o  \
VectorsModule.o  		trace_m.o  \
dates_module.o  		tree.o  \
declaration_table.o  		tree_types.o  \
dump_0.o  			units.o  \
error_handler.o  \
 
# using f90makedep.pl to calculate dependencies 
Allocate_Deallocate.o: Allocate_Deallocate.f90 MLSMessageModule.o
dates_module.o: dates_module.f90 MLSMessageModule.o MLSStrings.o
declaration_table.o: declaration_table.f90 intrinsic.o output_m.o \
	string_table.o toggles_core.o
dump_0.o: dump_0.f90 output_m.o
error_handler.o: error_handler.f90 output_m.o
expr_m.o: expr_m.f90 declaration_table.o intrinsic.o string_table.o \
	toggles_core.o trace_m.o tree.o tree_types.o
GriddedData.o: GriddedData.f90 MLSCommon.o MLSMessageModule.o MLSStrings.o \
	dates_module.o addItemToDatabase.f9h
Hdf.o: Hdf.f90 MLSCommon.o
heights_module.o: heights_module.f90 MLSCommon.o MLSMessageModule.o
intrinsic.o: intrinsic.f90 Molecules.o symbol_table.o symbol_types.o
L1BData.o: L1BData.f90 MLSCommon.o MLSMessageModule.o
L2GPData.o: L2GPData.f90 Allocate_Deallocate.o HDF-EOS.o Hdf.o MLSCommon.o \
	MLSMessageModule.o dump_0.o output_m.o string_table.o swapi.o \
	addItemToDatabase.f9h
lexer_core.o: lexer_core.f90 output_m.o string_table.o symbol_table.o \
	toggles_core.o
lexer_m.o: lexer_m.f90 error_handler.o lexer_core.o output_m.o string_table.o \
	symbol_table.o symbol_types.o toggles_core.o
ManipulateVectorQuantities.o: ManipulateVectorQuantities.f90 MLSCommon.o \
	MLSMessageModule.o MLSNumerics.o VectorsModule.o
MatrixModule_0.o: MatrixModule_0.f90 Allocate_Deallocate.o MLSCommon.o \
	MLSMessageModule.o dump_0.o output_m.o
MatrixModule_1.o: MatrixModule_1.f90 Allocate_Deallocate.o MLSCommon.o \
	MLSMessageModule.o MatrixModule_0.o VectorsModule.o dump_0.o \
	output_m.o string_table.o addItemToDatabase.f9h
MLSMessageModule.o: MLSMessageModule.f90 SDPToolkit.o
MLSNumerics.o: MLSNumerics.f90 Allocate_Deallocate.o MLSCommon.o \
	MLSMessageModule.o MLSStrings.o MatrixModule_0.o
MLSSignalNomenclature.o: MLSSignalNomenclature.f90 MLSCommon.o \
	MLSMessageModule.o MLSStrings.o intrinsic.o
MLSStrings.o: MLSStrings.f90 MLSMessageModule.o
Molecules.o: Molecules.f90 symbol_table.o symbol_types.o
MoreTree.o: MoreTree.f90 intrinsic.o tree.o tree_types.o
output_m.o: output_m.f90 MLSMessageModule.o
parser.o: parser.f90 lexer_core.o lexer_m.o output_m.o symbol_table.o \
	symbol_types.o toggles_core.o tree.o tree_types.o
QuantityTemplates.o: QuantityTemplates.f90 Allocate_Deallocate.o MLSCommon.o \
	MLSMessageModule.o intrinsic.o addItemToDatabase.f9h
SDPToolkit.o: SDPToolkit.f90 MLSCommon.o PGS_CBP.f PGS_CBP_6.f PGS_CSC_4.f \
	PGS_EPH_5.f PGS_IO.f PGS_IO_1.f PGS_MEM_7.f PGS_MET.f PGS_MET_13.f \
	PGS_PC.f PGS_PC_9.f PGS_SMF.f PGS_TD.f PGS_TD_3.f
string_table.o: string_table.f90 hash.o io_stuff.o output_m.o
swapi.o: swapi.f90 swapi_character_array.o swapi_character_scalar.o \
	swapi_double.o swapi_integer.o swapi_real.o
symbol_table.o: symbol_table.f90 output_m.o string_table.o symbol_types.o \
	toggles_core.o
symbol_types.o: symbol_types.f90 string_table.o
table_dumper.o: table_dumper.f90 MLSCF.o declaration_table.o intrinsic.o \
	output_m.o string_table.o
table_generator.o: table_generator.f90 MLSCF.o declaration_table.o expr_m.o \
	intrinsic.o lexer_core.o output_m.o string_table.o toggles_core.o \
	trace_m.o tree.o tree_types.o
trace_m.o: trace_m.f90 lexer_core.o output_m.o tree.o
tree.o: tree.f90 error_handler.o output_m.o string_table.o symbol_table.o \
	symbol_types.o toggles_core.o tree_types.o
tree_types.o: tree_types.f90 string_table.o symbol_types.o
units.o: units.f90 declaration_table.o intrinsic.o tree.o
VectorsModule.o: VectorsModule.f90 Allocate_Deallocate.o MLSCommon.o \
	MLSMessageModule.o QuantityTemplates.o dump_0.o output_m.o \
	string_table.o addItemToDatabase.f9h
 
#End of Makefile.dep
 
