# $Id$

# Fortran compiler:
FC = lf95

# Compiler options:
FOPTS = -g --chk --info
#FOPTS = -O

# Path to source files:
S = ..

# Path to .mod files:
M = $(HOME)/mlspgs/lib/LF95

# Option to specify path to .mod files:
I = -I

# Beginning of path to toolkit libraries:
TOOLKIT = /software/SRC/TOOLKIT-5.2.6v1.00.NAG

# Beginning of path to HDFEOS libraries:
HDFEOS = /van1/opt/TOOLKIT
#HDFEOS = $(TOOLKIT)

# Path to Configuration parser
C = $(HOME)/mlspgs/lib/cf_parser/LF95

# Platform (used within directory paths in ../Makefile.inc):
PLATFORM = linux

# Path to libPGSTK.a
PGSTK = $(HOME)/mlspgs/SDPToolkit/LF95
#PGSTK = $(TOOLKIT)/lib/$(PLATFORM)

include $S/Makefile.inc

# $Log$
