#Makefile.dep -- a file to be included by a Makefile
#to compile a Fortran 9x program or library
OBJS = \
ChunkDivide_m.o   Construct.o   ConstructQuantityTemplates.o   ConstructVectorTemplates.o   EmpiricalGeometry.o   FGrid.o   Fill.o   ForwardModelSupport.o   ForwardModelWrappers.o   HGrid.o   Join.o   L2AUXData.o   L2ParInfo.o   L2Parallel.o   MLSL2.o   MLSL2Common.o   MLSL2Options.o   MLSL2Timings.o   MLSPCF2.o   MatrixTools.o   MergeGridsModule.o   OutputAndClose.o   Regularization.o   RetrievalModule.o   ScanModelModule.o   SidsModule.o   SnoopMLSL2.o   TestCholesky_m.o   Test_Parse_Signals_m.o   VGrid.o   dnwt_clone.o   dnwt_module.o   dnwt_type.o   dumper.o   ermsg_m.o   global_settings.o   init_tables_module.o   obtain_mlscf.o   open_init.o   read_apriori.o   tree_walker.o   write_meta.o  \
\
\
 
# using f90makedep.pl to calculate dependencies 
ChunkDivide_m.o: ChunkDivide_m.f90 $(dir1)Allocate_Deallocate.o \
	$(dir1)L1BData.o $(dir1)MLSCommon.o $(dir1)MLSMessageModule.o \
	$(dir1)MLSNumerics.o $(dir1)MLSSignals_m.o $(dir1)MoreTree.o \
	$(dir1)dump_0.o $(dir1)expr_m.o $(dir1)intrinsic.o \
	$(dir1)lexer_core.o $(dir1)output_m.o $(dir1)string_table.o \
	$(dir1)time_m.o $(dir1)toggles_core.o $(dir1)trace_m.o \
	$(dir1)tree_types.o $(dir1)units.o $(dir2)tree.o MLSL2Timings.o \
	dumper.o init_tables_module.o addItemToDatabase.f9h
Construct.o: Construct.f90 $(dir1)Allocate_Deallocate.o $(dir1)L2GPData.o \
	$(dir1)MLSCommon.o $(dir1)MLSMessageModule.o $(dir1)MLSSignals_m.o \
	$(dir1)MoreTree.o $(dir1)QuantityTemplates.o $(dir1)VGridsDatabase.o \
	$(dir1)VectorsModule.o $(dir1)intrinsic.o $(dir1)output_m.o \
	$(dir1)string_table.o $(dir1)time_m.o $(dir1)toggles_core.o \
	$(dir1)trace_m.o $(dir1)tree_types.o $(dir2)tree.o \
	ConstructQuantityTemplates.o ConstructVectorTemplates.o FGrid.o \
	HGrid.o MLSL2Timings.o dumper.o init_tables_module.o
ConstructQuantityTemplates.o: ConstructQuantityTemplates.f90 \
	$(dir1)Allocate_Deallocate.o $(dir1)L1BData.o $(dir1)MLSCommon.o \
	$(dir1)MLSMessageModule.o $(dir1)MLSSignals_m.o \
	$(dir1)Parse_Signal_m.o $(dir1)QuantityTemplates.o \
	$(dir1)VGridsDatabase.o $(dir1)expr_m.o $(dir1)lexer_core.o \
	$(dir1)output_m.o $(dir1)string_table.o $(dir1)toggles_core.o \
	$(dir1)trace_m.o $(dir1)tree_types.o $(dir2)tree.o FGrid.o HGrid.o \
	init_tables_module.o
ConstructVectorTemplates.o: ConstructVectorTemplates.f90 \
	$(dir1)Allocate_Deallocate.o $(dir1)MLSMessageModule.o \
	$(dir1)QuantityTemplates.o $(dir1)VectorsModule.o $(dir1)output_m.o \
	$(dir1)string_table.o $(dir1)toggles_core.o $(dir1)trace_m.o \
	$(dir2)tree.o init_tables_module.o
dnwt_clone.o: dnwt_clone.f90 dnwt_module.o dnwt_type.o
dnwt_module.o: dnwt_module.f90 $(dir1)output_m.o dnwt_type.o ermsg_m.o
dumper.o: dumper.f90 $(dir1)MLSCommon.o $(dir1)MLSSignals_m.o \
	$(dir1)QuantityTemplates.o $(dir1)dump_0.o $(dir1)intrinsic.o \
	$(dir1)output_m.o $(dir1)string_table.o HGrid.o
EmpiricalGeometry.o: EmpiricalGeometry.f90 $(dir1)Allocate_Deallocate.o \
	$(dir1)L1BData.o $(dir1)MLSCommon.o $(dir1)MLSMessageModule.o \
	$(dir1)MoreTree.o $(dir1)expr_m.o $(dir1)units.o $(dir2)tree.o \
	init_tables_module.o
ermsg_m.o: ermsg_m.f90 $(dir1)output_m.o
FGrid.o: FGrid.f90 $(dir1)Allocate_Deallocate.o $(dir1)MLSCommon.o \
	$(dir1)MLSMessageModule.o $(dir1)expr_m.o $(dir1)intrinsic.o \
	$(dir1)units.o $(dir2)tree.o init_tables_module.o \
	addItemToDatabase.f9h
Fill.o: Fill.f90 $(dir1)Allocate_Deallocate.o $(dir1)GriddedData.o \
	$(dir1)L1BData.o $(dir1)L2GPData.o $(dir1)MLSCommon.o \
	$(dir1)MLSMessageModule.o $(dir1)MLSNumerics.o \
	$(dir1)MLSRandomNumber.o $(dir1)MLSSignals_m.o \
	$(dir1)ManipulateVectorQuantities.o $(dir1)MatrixModule_0.o \
	$(dir1)MatrixModule_1.o $(dir1)Molecules.o $(dir1)MoreTree.o \
	$(dir1)QuantityTemplates.o $(dir1)VGridsDatabase.o \
	$(dir1)VectorsModule.o $(dir1)expr_m.o $(dir1)intrinsic.o \
	$(dir1)l3ascii.o $(dir1)lexer_core.o $(dir1)output_m.o \
	$(dir1)string_table.o $(dir1)time_m.o $(dir1)toggles_core.o \
	$(dir1)trace_m.o $(dir1)tree_types.o $(dir1)units.o $(dir2)tree.o \
	L2AUXData.o MLSL2Timings.o ScanModelModule.o SnoopMLSL2.o \
	init_tables_module.o
ForwardModelSupport.o: ForwardModelSupport.f90 $(dir1)Allocate_Deallocate.o \
	$(dir1)L2PC_m.o $(dir1)MLSCommon.o $(dir1)MLSFiles.o \
	$(dir1)MLSMessageModule.o $(dir1)MLSNumerics.o $(dir1)MLSSignals_m.o \
	$(dir1)MoreTree.o $(dir1)Parse_Signal_m.o $(dir1)VGridsDatabase.o \
	$(dir1)expr_m.o $(dir1)lexer_core.o $(dir1)output_m.o \
	$(dir1)string_table.o $(dir1)toggles_core.o $(dir1)trace_m.o \
	$(dir1)tree_types.o $(dir1)units.o $(dir2)tree.o \
	$(dir3)AntennaPatterns_m.o $(dir3)FilterShapes_m.o \
	$(dir3)ForwardModelConfig.o $(dir3)PointingGrid_m.o L2ParInfo.o \
	MLSL2Options.o MLSPCF2.o init_tables_module.o
ForwardModelWrappers.o: ForwardModelWrappers.f90 $(dir1)MatrixModule_1.o \
	$(dir1)VectorsModule.o $(dir3)BaselineForwardModel_m.o \
	$(dir3)ForwardModelConfig.o $(dir3)ForwardModelIntermediate.o \
	$(dir3)FullForwardModel_m.o $(dir3)LinearizedForwardModel_m.o \
	$(dir4)FullCloudForwardModel.o MLSL2Timings.o ScanModelModule.o \
	init_tables_module.o
global_settings.o: global_settings.f90 $(dir1)L1BData.o $(dir1)L2GPData.o \
	$(dir1)L2PC_m.o $(dir1)MLSCommon.o $(dir1)MLSMessageModule.o \
	$(dir1)MLSSignals_m.o $(dir1)MLSStrings.o $(dir1)MoreTree.o \
	$(dir1)SDPToolkit.o $(dir1)VGridsDatabase.o $(dir1)lexer_core.o \
	$(dir1)output_m.o $(dir1)string_table.o $(dir1)time_m.o \
	$(dir1)toggles_core.o $(dir1)trace_m.o $(dir1)tree_types.o \
	$(dir2)tree.o $(dir3)ForwardModelConfig.o EmpiricalGeometry.o FGrid.o \
	ForwardModelSupport.o MLSL2Options.o MLSL2Timings.o MLSPCF2.o VGrid.o \
	init_tables_module.o write_meta.o
HGrid.o: HGrid.f90 $(dir1)Allocate_Deallocate.o $(dir1)L1BData.o \
	$(dir1)L2GPData.o $(dir1)MLSCommon.o $(dir1)MLSMessageModule.o \
	$(dir1)MLSNumerics.o $(dir1)MoreTree.o $(dir1)dump_0.o \
	$(dir1)expr_m.o $(dir1)lexer_core.o $(dir1)output_m.o \
	$(dir1)string_table.o $(dir1)toggles_core.o $(dir1)trace_m.o \
	$(dir1)units.o $(dir2)tree.o EmpiricalGeometry.o init_tables_module.o \
	addItemToDatabase.f9h
init_tables_module.o: init_tables_module.f90 $(dir1)Allocate_Deallocate.o \
	$(dir1)Init_MLSSignals_m.o $(dir1)MLSMessageModule.o \
	$(dir1)Molecules.o $(dir1)intrinsic.o $(dir1)tree_types.o \
	$(dir1)units.o $(dir2)tree.o $(dir3)Init_Spectroscopy_m.o \
	field_add.f9h field_parm.f9h lit_add.f9h lit_parm.f9h make_tree.f9h
Join.o: Join.f90 $(dir1)L2GPData.o $(dir1)MLSCommon.o \
	$(dir1)MLSMessageModule.o $(dir1)MLSSignals_m.o \
	$(dir1)ManipulateVectorQuantities.o $(dir1)MoreTree.o \
	$(dir1)VectorsModule.o $(dir1)intrinsic.o $(dir1)lexer_core.o \
	$(dir1)output_m.o $(dir1)string_table.o $(dir1)symbol_table.o \
	$(dir1)symbol_types.o $(dir1)time_m.o $(dir1)toggles_core.o \
	$(dir1)trace_m.o $(dir1)tree_types.o $(dir2)tree.o L2AUXData.o \
	L2ParInfo.o MLSL2Timings.o OutputAndClose.o init_tables_module.o
L2AUXData.o: L2AUXData.f90 $(dir1)Allocate_Deallocate.o $(dir1)Hdf.o \
	$(dir1)MLSCommon.o $(dir1)MLSMessageModule.o $(dir1)MLSSignals_m.o \
	$(dir1)MLSStrings.o $(dir1)dump_0.o $(dir1)intrinsic.o \
	$(dir1)lexer_core.o $(dir1)output_m.o $(dir1)string_table.o \
	$(dir2)tree.o addItemToDatabase.f9h
L2Parallel.o: L2Parallel.f90 $(dir1)Allocate_Deallocate.o $(dir1)L2GPData.o \
	$(dir1)MLSCommon.o $(dir1)MLSMessageModule.o $(dir1)MoreTree.o \
	$(dir1)PVM.o $(dir1)PVMIDL.o $(dir1)QuantityPVM.o \
	$(dir1)QuantityTemplates.o $(dir1)VectorsModule.o $(dir1)dump_0.o \
	$(dir1)output_m.o $(dir1)string_table.o $(dir1)symbol_table.o \
	$(dir1)symbol_types.o $(dir1)toggles_core.o Join.o L2AUXData.o \
	L2ParInfo.o dumper.o init_tables_module.o addItemToDatabase.f9h
L2ParInfo.o: L2ParInfo.f90 $(dir1)MLSMessageModule.o $(dir1)MLSStrings.o \
	$(dir1)PVM.o $(dir1)PVMIDL.o $(dir1)QuantityPVM.o \
	$(dir1)VectorsModule.o
MatrixTools.o: MatrixTools.f90 $(dir1)Allocate_Deallocate.o \
	$(dir1)MLSCommon.o $(dir1)MLSMessageModule.o $(dir1)MatrixModule_0.o \
	$(dir1)MatrixModule_1.o $(dir1)MoreTree.o $(dir1)PVM.o \
	$(dir1)PVMIDL.o $(dir1)QuantityPVM.o $(dir1)VectorsModule.o \
	$(dir1)declaration_table.o $(dir1)dump_0.o $(dir1)expr_m.o \
	$(dir1)output_m.o $(dir1)string_table.o $(dir2)tree.o \
	init_tables_module.o
MergeGridsModule.o: MergeGridsModule.f90 $(dir1)GriddedData.o \
	$(dir1)MLSCommon.o $(dir1)MLSMessageModule.o $(dir1)MoreTree.o \
	$(dir1)expr_m.o $(dir1)l3ascii.o $(dir1)toggles_core.o \
	$(dir1)trace_m.o $(dir1)tree_types.o $(dir1)units.o $(dir2)tree.o \
	init_tables_module.o
MLSL2.o: MLSL2.f90 $(dir1)Allocate_Deallocate.o $(dir1)MLSCommon.o \
	$(dir1)MLSMessageModule.o $(dir1)MatrixModule_0.o $(dir1)PVM.o \
	$(dir1)SDPToolkit.o $(dir1)declaration_table.o $(dir1)lexer_core.o \
	$(dir1)lexer_m.o $(dir1)output_m.o $(dir1)parser.o \
	$(dir1)string_table.o $(dir1)symbol_table.o $(dir1)time_m.o \
	$(dir1)toggles_core.o $(dir2)tree.o $(dir2)tree_checker.o L2ParInfo.o \
	MLSL2Options.o MLSL2Timings.o MLSPCF2.o SnoopMLSL2.o \
	init_tables_module.o obtain_mlscf.o tree_walker.o
MLSL2Common.o: MLSL2Common.f90 $(dir1)MLSCommon.o $(dir1)MLSMessageModule.o
MLSL2Options.o: MLSL2Options.f90 $(dir1)MLSFiles.o $(dir1)MLSMessageModule.o
MLSL2Timings.o: MLSL2Timings.f90 $(dir1)MLSMessageModule.o \
	$(dir1)MLSStrings.o $(dir1)output_m.o $(dir1)time_m.o
obtain_mlscf.o: obtain_mlscf.f90 $(dir1)MLSFiles.o $(dir1)SDPToolkit.o \
	$(dir1)lexer_core.o $(dir1)output_m.o $(dir2)tree.o
open_init.o: open_init.f90 $(dir1)Hdf.o $(dir1)L1BData.o $(dir1)MLSCommon.o \
	$(dir1)MLSFiles.o $(dir1)MLSMessageModule.o $(dir1)MLSStrings.o \
	$(dir1)PCFHdr.o $(dir1)SDPToolkit.o $(dir1)lexer_core.o \
	$(dir1)output_m.o $(dir1)time_m.o $(dir1)toggles_core.o \
	$(dir1)trace_m.o $(dir2)tree.o MLSL2Options.o MLSL2Timings.o \
	MLSPCF2.o global_settings.o write_meta.o
OutputAndClose.o: OutputAndClose.f90 $(dir1)Allocate_Deallocate.o \
	$(dir1)Hdf.o $(dir1)L2GPData.o $(dir1)L2PC_m.o $(dir1)MLSCommon.o \
	$(dir1)MLSFiles.o $(dir1)MLSMessageModule.o $(dir1)MatrixModule_1.o \
	$(dir1)MoreTree.o $(dir1)SDPToolkit.o $(dir1)expr_m.o \
	$(dir1)intrinsic.o $(dir1)lexer_core.o $(dir1)output_m.o \
	$(dir1)string_table.o $(dir1)time_m.o $(dir1)toggles_core.o \
	$(dir1)trace_m.o $(dir1)tree_types.o $(dir2)tree.o L2AUXData.o \
	MLSL2Options.o MLSL2Timings.o MLSPCF2.o init_tables_module.o \
	write_meta.o
read_apriori.o: read_apriori.f90 $(dir1)GriddedData.o $(dir1)Hdf.o \
	$(dir1)L2GPData.o $(dir1)MLSCommon.o $(dir1)MLSFiles.o \
	$(dir1)MLSMessageModule.o $(dir1)MoreTree.o $(dir1)SDPToolkit.o \
	$(dir1)expr_m.o $(dir1)intrinsic.o $(dir1)lexer_core.o \
	$(dir1)ncep_dao.o $(dir1)output_m.o $(dir1)string_table.o \
	$(dir1)time_m.o $(dir1)toggles_core.o $(dir1)trace_m.o \
	$(dir1)tree_types.o $(dir2)tree.o L2AUXData.o MLSL2Options.o \
	MLSL2Timings.o MLSPCF2.o init_tables_module.o
Regularization.o: Regularization.f90 $(dir1)MLSCommon.o \
	$(dir1)MLSMessageModule.o $(dir1)MatrixModule_0.o \
	$(dir1)MatrixModule_1.o $(dir1)expr_m.o $(dir1)intrinsic.o \
	$(dir1)lexer_core.o $(dir1)output_m.o $(dir2)tree.o
RetrievalModule.o: RetrievalModule.f90 $(dir1)Allocate_Deallocate.o \
	$(dir1)BitStuff.o $(dir1)MLSCommon.o $(dir1)MLSMessageModule.o \
	$(dir1)MLSNumerics.o $(dir1)MLSSignals_m.o $(dir1)MLSStrings.o \
	$(dir1)MatrixModule_0.o $(dir1)MatrixModule_1.o $(dir1)MoreTree.o \
	$(dir1)VectorsModule.o $(dir1)declaration_table.o $(dir1)dump_0.o \
	$(dir1)expr_m.o $(dir1)intrinsic.o $(dir1)lexer_core.o \
	$(dir1)output_m.o $(dir1)string_table.o $(dir1)symbol_table.o \
	$(dir1)symbol_types.o $(dir1)time_m.o $(dir1)toggles_core.o \
	$(dir1)trace_m.o $(dir1)tree_types.o $(dir1)units.o $(dir2)tree.o \
	$(dir3)ForwardModelConfig.o $(dir3)ForwardModelIntermediate.o \
	ForwardModelWrappers.o MLSL2Timings.o MatrixTools.o Regularization.o \
	SidsModule.o SnoopMLSL2.o dnwt_module.o init_tables_module.o
ScanModelModule.o: ScanModelModule.f90 $(dir1)Allocate_Deallocate.o \
	$(dir1)Geometry.o $(dir1)MLSCommon.o $(dir1)MLSMessageModule.o \
	$(dir1)MLSNumerics.o $(dir1)ManipulateVectorQuantities.o \
	$(dir1)MatrixModule_0.o $(dir1)MatrixModule_1.o $(dir1)Molecules.o \
	$(dir1)VectorsModule.o $(dir1)dump_0.o $(dir1)intrinsic.o \
	$(dir1)output_m.o $(dir1)toggles_core.o $(dir1)trace_m.o \
	$(dir1)units.o $(dir3)ForwardModelConfig.o \
	$(dir3)ForwardModelIntermediate.o init_tables_module.o
SidsModule.o: SidsModule.f90 $(dir1)Allocate_Deallocate.o $(dir1)MLSCommon.o \
	$(dir1)MLSMessageModule.o $(dir1)MatrixModule_0.o \
	$(dir1)MatrixModule_1.o $(dir1)MoreTree.o $(dir1)VectorsModule.o \
	$(dir1)dump_0.o $(dir1)lexer_core.o $(dir1)output_m.o $(dir1)time_m.o \
	$(dir1)toggles_core.o $(dir1)trace_m.o $(dir2)tree.o \
	$(dir3)ForwardModelConfig.o $(dir3)ForwardModelIntermediate.o \
	ForwardModelWrappers.o MLSL2Timings.o init_tables_module.o
SnoopMLSL2.o: SnoopMLSL2.f90 $(dir1)MLSCommon.o $(dir1)MLSMessageModule.o \
	$(dir1)MLSSignals_m.o $(dir1)MatrixModule_0.o $(dir1)MatrixModule_1.o \
	$(dir1)MoreTree.o $(dir1)PVM.o $(dir1)PVMIDL.o $(dir1)QuantityPVM.o \
	$(dir1)QuantityTemplates.o $(dir1)VectorsModule.o $(dir1)intrinsic.o \
	$(dir1)lexer_core.o $(dir1)output_m.o $(dir1)string_table.o \
	$(dir1)symbol_table.o $(dir1)symbol_types.o $(dir2)tree.o \
	init_tables_module.o addItemToDatabase.f9h
Test_Parse_Signals_m.o: Test_Parse_Signals_m.f90 $(dir1)Allocate_Deallocate.o \
	$(dir1)MLSSignals_m.o $(dir1)Parse_Signal_m.o
TestCholesky_m.o: TestCholesky_m.f90 $(dir1)Biggify_M.o $(dir1)MLSCommon.o \
	$(dir1)MatrixModule_0.o $(dir1)MatrixModule_1.o
tree_walker.o: tree_walker.f90 $(dir1)GriddedData.o $(dir1)L2GPData.o \
	$(dir1)L2PC_m.o $(dir1)MLSCommon.o $(dir1)MLSSignals_m.o \
	$(dir1)MatrixModule_1.o $(dir1)QuantityTemplates.o \
	$(dir1)VGridsDatabase.o $(dir1)VectorsModule.o $(dir1)output_m.o \
	$(dir1)time_m.o $(dir1)toggles_core.o $(dir1)trace_m.o $(dir2)tree.o \
	$(dir3)AntennaPatterns_m.o $(dir3)FilterShapes_m.o \
	$(dir3)ForwardModelConfig.o $(dir3)PointingGrid_m.o \
	$(dir3)SpectroscopyCatalog_m.o ChunkDivide_m.o Construct.o \
	EmpiricalGeometry.o FGrid.o Fill.o HGrid.o Join.o L2AUXData.o \
	L2ParInfo.o L2Parallel.o MLSL2Options.o MLSL2Timings.o \
	MergeGridsModule.o OutputAndClose.o RetrievalModule.o \
	Test_Parse_Signals_m.o dumper.o global_settings.o \
	init_tables_module.o open_init.o read_apriori.o write_meta.o
VGrid.o: VGrid.f90 $(dir1)Allocate_Deallocate.o $(dir1)L2GPData.o \
	$(dir1)MLSCommon.o $(dir1)MLSMessageModule.o $(dir1)VGridsDatabase.o \
	$(dir1)expr_m.o $(dir1)intrinsic.o $(dir1)lexer_core.o \
	$(dir1)output_m.o $(dir1)string_table.o $(dir1)toggles_core.o \
	$(dir1)trace_m.o $(dir2)tree.o init_tables_module.o
write_meta.o: write_meta.f90 $(dir1)Hdf.o $(dir1)MLSCommon.o \
	$(dir1)MLSFiles.o $(dir1)MLSMessageModule.o $(dir1)MLSStrings.o \
	$(dir1)PCFHdr.o $(dir1)SDPToolkit.o $(dir1)lexer_core.o \
	$(dir1)output_m.o $(dir1)toggles_core.o $(dir2)tree.o MLSL2Options.o \
	MLSPCF2.o
 
#End of Makefile.dep
 
