#Makefile.dep -- a file to be included by a Makefile
#to compile a Fortran 9x program or library
OBJS = \
Construct.o  			SidsModule.o  \
ConstructQuantityTemplates.o  	SnoopMLSL2.o  \
ConstructVectorTemplates.o  	Test_Parse_Signals_m.o  \
Fill.o  			VGrid.o  \
ForwardModelInterface.o  	dnwt_module.o  \
HGrid.o  			dnwt_type.o  \
Join.o  			dumper.o  \
L2AUXData.o  			ermsg_m.o  \
MLSL2.o  			global_settings.o  \
MLSL2Common.o  			init_tables_module.o  \
MLSPCF2.o  			obtain_mlscf.o  \
OutputAndClose.o  		open_init.o  \
RetrievalModule.o  		read_apriori.o  \
ScanDivide.o  			tree_walker.o  \
ScanModelModule.o  		write_meta.o  \
 
# using f90makedep.pl to calculate dependencies 
Construct.o: Construct.f90 $(dir1)Allocate_Deallocate.o $(dir1)MLSCommon.o \
	$(dir1)MLSMessageModule.o $(dir1)MLSSignals_m.o $(dir1)MoreTree.o \
	$(dir1)QuantityTemplates.o $(dir1)VectorsModule.o $(dir1)intrinsic.o \
	$(dir1)output_m.o $(dir1)string_table.o $(dir1)toggles_core.o \
	$(dir1)trace_m.o $(dir1)tree.o $(dir1)tree_types.o \
	ConstructQuantityTemplates.o ConstructVectorTemplates.o HGrid.o \
	VGrid.o dumper.o init_tables_module.o
ConstructQuantityTemplates.o: ConstructQuantityTemplates.f90 \
	$(dir1)Allocate_Deallocate.o $(dir1)L1BData.o $(dir1)MLSCommon.o \
	$(dir1)MLSMessageModule.o $(dir1)MLSSignals_m.o \
	$(dir1)QuantityTemplates.o $(dir1)lexer_core.o $(dir1)output_m.o \
	$(dir1)string_table.o $(dir1)toggles_core.o $(dir1)trace_m.o \
	$(dir1)tree.o $(dir1)tree_types.o HGrid.o VGrid.o \
	init_tables_module.o
ConstructVectorTemplates.o: ConstructVectorTemplates.f90 \
	$(dir1)Allocate_Deallocate.o $(dir1)MLSMessageModule.o \
	$(dir1)QuantityTemplates.o $(dir1)VectorsModule.o $(dir1)output_m.o \
	$(dir1)string_table.o $(dir1)toggles_core.o $(dir1)trace_m.o \
	$(dir1)tree.o init_tables_module.o
dnwt_module.o: dnwt_module.f90 dnwt_type.o ermsg_m.o
dumper.o: dumper.f90 $(dir1)MLSCommon.o $(dir1)MLSSignals_m.o \
	$(dir1)QuantityTemplates.o $(dir1)dump_0.o $(dir1)output_m.o \
	$(dir1)string_table.o HGrid.o VGrid.o init_tables_module.o
Fill.o: Fill.f90 $(dir1)Allocate_Deallocate.o $(dir1)GriddedData.o \
	$(dir1)L1BData.o $(dir1)L2GPData.o $(dir1)MLSCommon.o \
	$(dir1)MLSMessageModule.o $(dir1)MLSSignals_m.o $(dir1)Molecules.o \
	$(dir1)MoreTree.o $(dir1)QuantityTemplates.o $(dir1)VectorsModule.o \
	$(dir1)expr_m.o $(dir1)intrinsic.o $(dir1)lexer_core.o \
	$(dir1)output_m.o $(dir1)string_table.o $(dir1)toggles_core.o \
	$(dir1)trace_m.o $(dir1)tree.o $(dir1)tree_types.o L2AUXData.o \
	ScanModelModule.o SnoopMLSL2.o init_tables_module.o
ForwardModelInterface.o: ForwardModelInterface.f90 \
	$(dir1)Allocate_Deallocate.o $(dir1)MLSCommon.o \
	$(dir1)MLSMessageModule.o $(dir1)MLSSignals_m.o \
	$(dir1)MatrixModule_1.o $(dir1)MoreTree.o $(dir1)VectorsModule.o \
	$(dir1)declaration_table.o $(dir1)dump_0.o $(dir1)expr_m.o \
	$(dir1)lexer_core.o $(dir1)output_m.o $(dir1)string_table.o \
	$(dir1)toggles_core.o $(dir1)trace_m.o $(dir1)tree.o \
	$(dir1)tree_types.o $(dir3)PointingGrid_m.o \
	$(dir3)comp_path_entities_m.o $(dir3)convolve_all_m.o \
	$(dir3)d_hunt_m.o $(dir3)ellipse.o $(dir3)freq_avg_m.o \
	$(dir3)geoc_geod_conv_m.o $(dir3)get_beta_path_m.o \
	$(dir3)get_chi_angles_m.o $(dir3)gl6p.o $(dir3)hydrostatic_model_m.o \
	$(dir3)l2_load_m.o $(dir3)l2_test_structures_m.o \
	$(dir3)l2pc_file_parameters.o $(dir3)l2pc_pfa_structures.o \
	$(dir3)l2pcdim.o $(dir3)no_conv_at_all_m.o $(dir3)path_entities.o \
	$(dir3)ptg_frq_load_m.o $(dir3)rad_tran_m.o $(dir3)refraction_m.o \
	init_tables_module.o addItemToDatabase.f9h
global_settings.o: global_settings.f90 $(dir1)MLSCommon.o \
	$(dir1)MLSMessageModule.o $(dir1)MoreTree.o $(dir1)string_table.o \
	$(dir1)toggles_core.o $(dir1)trace_m.o $(dir1)tree.o \
	$(dir1)tree_types.o $(dir3)l2_load_m.o $(dir3)l2_test_structures_m.o \
	ForwardModelInterface.o init_tables_module.o
HGrid.o: HGrid.f90 $(dir1)L1BData.o $(dir1)MLSCommon.o \
	$(dir1)MLSMessageModule.o $(dir1)MLSNumerics.o $(dir1)expr_m.o \
	$(dir1)lexer_core.o $(dir1)output_m.o $(dir1)string_table.o \
	$(dir1)toggles_core.o $(dir1)trace_m.o $(dir1)tree.o \
	init_tables_module.o addItemToDatabase.f9h
init_tables_module.o: init_tables_module.f90 $(dir1)Init_MLSSignals_m.o \
	$(dir1)intrinsic.o $(dir1)tree_types.o make_tree.f9h
Join.o: Join.f90 $(dir1)L2GPData.o $(dir1)MLSCommon.o \
	$(dir1)MLSMessageModule.o $(dir1)MoreTree.o \
	$(dir1)QuantityTemplates.o $(dir1)SDPToolkit.o $(dir1)VectorsModule.o \
	$(dir1)intrinsic.o $(dir1)lexer_core.o $(dir1)output_m.o \
	$(dir1)string_table.o $(dir1)toggles_core.o $(dir1)trace_m.o \
	$(dir1)tree.o $(dir1)tree_types.o L2AUXData.o init_tables_module.o
L2AUXData.o: L2AUXData.f90 $(dir1)Allocate_Deallocate.o $(dir1)Hdf.o \
	$(dir1)MLSCommon.o $(dir1)MLSMessageModule.o $(dir1)MLSSignals_m.o \
	$(dir1)MLSStrings.o $(dir1)SDPToolkit.o $(dir1)dump_0.o \
	$(dir1)intrinsic.o $(dir1)output_m.o $(dir1)string_table.o \
	init_tables_module.o addItemToDatabase.f9h
MLSL2Common.o: MLSL2Common.f90 $(dir1)MLSCommon.o $(dir1)MLSMessageModule.o
MLSL2.o: MLSL2.f90 $(dir1)MLSMessageModule.o $(dir1)declaration_table.o \
	$(dir1)lexer_core.o $(dir1)lexer_m.o $(dir1)output_m.o \
	$(dir1)parser.o $(dir1)string_table.o $(dir1)toggles_core.o \
	$(dir1)tree.o $(dir1)units.o $(dir2)tree_checker.o MLSPCF2.o \
	init_tables_module.o obtain_mlscf.o tree_walker.o
obtain_mlscf.o: obtain_mlscf.f90 $(dir1)MLSMessageModule.o \
	$(dir1)SDPToolkit.o
open_init.o: open_init.f90 $(dir1)HDF-EOS.o $(dir1)Hdf.o $(dir1)L2GPData.o \
	$(dir1)MLSCommon.o $(dir1)MLSMessageModule.o \
	$(dir1)MLSSignalNomenclature.o $(dir1)MoreTree.o $(dir1)SDPToolkit.o \
	$(dir1)string_table.o $(dir1)toggles_core.o $(dir1)trace_m.o \
	$(dir1)tree.o $(dir1)tree_types.o L2AUXData.o MLSPCF2.o \
	init_tables_module.o
OutputAndClose.o: OutputAndClose.f90 $(dir1)HDF-EOS.o $(dir1)Hdf.o \
	$(dir1)L2GPData.o $(dir1)MLSCommon.o $(dir1)MLSMessageModule.o \
	$(dir1)MoreTree.o $(dir1)SDPToolkit.o $(dir1)lexer_core.o \
	$(dir1)output_m.o $(dir1)string_table.o $(dir1)toggles_core.o \
	$(dir1)trace_m.o $(dir1)tree.o $(dir1)tree_types.o L2AUXData.o \
	MLSPCF2.o init_tables_module.o
read_apriori.o: read_apriori.f90 $(dir1)GriddedData.o $(dir1)HDF-EOS.o \
	$(dir1)Hdf.o $(dir1)L2GPData.o $(dir1)MLSCommon.o \
	$(dir1)MLSMessageModule.o $(dir1)MoreTree.o $(dir1)ncep_dao.o \
	$(dir1)output_m.o $(dir1)string_table.o $(dir1)toggles_core.o \
	$(dir1)trace_m.o $(dir1)tree.o $(dir1)tree_types.o L2AUXData.o \
	MLSPCF2.o init_tables_module.o
RetrievalModule.o: RetrievalModule.f90 $(dir1)MLSCommon.o \
	$(dir1)MatrixModule_1.o $(dir1)MoreTree.o $(dir1)VectorsModule.o \
	$(dir1)expr_m.o $(dir1)lexer_core.o $(dir1)output_m.o \
	$(dir1)string_table.o $(dir1)toggles_core.o $(dir1)trace_m.o \
	$(dir1)tree.o $(dir1)tree_types.o $(dir3)l2_test_structures_m.o \
	ForwardModelInterface.o SidsModule.o dnwt_module.o \
	init_tables_module.o
ScanDivide.o: ScanDivide.f90 $(dir1)L1BData.o $(dir1)MLSCommon.o \
	$(dir1)MLSMessageModule.o $(dir1)MLSNumerics.o $(dir1)SDPToolkit.o \
	$(dir1)expr_m.o $(dir1)lexer_core.o $(dir1)output_m.o \
	$(dir1)string_table.o $(dir1)tree.o init_tables_module.o
ScanModelModule.o: ScanModelModule.f90 $(dir1)Allocate_Deallocate.o \
	$(dir1)MLSCommon.o $(dir1)MLSMessageModule.o $(dir1)MLSNumerics.o \
	$(dir1)ManipulateVectorQuantities.o $(dir1)VectorsModule.o \
	$(dir1)dump_0.o $(dir1)intrinsic.o $(dir1)output_m.o \
	init_tables_module.o
SidsModule.o: SidsModule.f90 $(dir1)MatrixModule_1.o $(dir1)MoreTree.o \
	$(dir1)VectorsModule.o $(dir1)lexer_core.o $(dir1)output_m.o \
	$(dir1)toggles_core.o $(dir1)trace_m.o $(dir1)tree.o \
	$(dir3)l2_test_structures_m.o ForwardModelInterface.o \
	init_tables_module.o
SnoopMLSL2.o: SnoopMLSL2.f90 $(dir1)MLSCommon.o $(dir1)MLSMessageModule.o \
	$(dir1)PVM.o $(dir1)PVMIDL.o $(dir1)VectorsModule.o \
	$(dir1)lexer_core.o $(dir1)output_m.o $(dir1)string_table.o \
	$(dir1)tree.o
Test_Parse_Signals_m.o: Test_Parse_Signals_m.f90 $(dir1)Allocate_Deallocate.o \
	$(dir1)MLSSignals_m.o $(dir1)Parse_Signal_m.o init_tables_module.o
tree_walker.o: tree_walker.f90 $(dir1)GriddedData.o $(dir1)L2GPData.o \
	$(dir1)MLSCommon.o $(dir1)MLSSignals_m.o $(dir1)MatrixModule_1.o \
	$(dir1)QuantityTemplates.o $(dir1)VectorsModule.o $(dir1)ncep_dao.o \
	$(dir1)toggles_core.o $(dir1)trace_m.o $(dir1)tree.o \
	$(dir1)tree_types.o $(dir3)l2_test_structures_m.o Construct.o Fill.o \
	ForwardModelInterface.o Join.o L2AUXData.o OutputAndClose.o \
	RetrievalModule.o ScanDivide.o dumper.o global_settings.o \
	init_tables_module.o open_init.o read_apriori.o
VGrid.o: VGrid.f90 $(dir1)MLSCommon.o $(dir1)MLSMessageModule.o \
	$(dir1)expr_m.o $(dir1)lexer_core.o $(dir1)output_m.o \
	$(dir1)string_table.o $(dir1)toggles_core.o $(dir1)trace_m.o \
	$(dir1)tree.o init_tables_module.o addItemToDatabase.f9h
write_meta.o: write_meta.f90 $(dir1)HDF-EOS.o $(dir1)Hdf.o $(dir1)L2GPData.o \
	$(dir1)MLSCF.o $(dir1)MLSCommon.o $(dir1)MLSMessageModule.o \
	$(dir1)MLSStrings.o $(dir1)SDPToolkit.o L2AUXData.o MLSPCF2.o
 
#End of Makefile.dep
 
