! Copyright 2005, by the California Institute of Technology. ALL
! RIGHTS RESERVED. United States Government Sponsorship acknowledged. Any
! commercial use must be negotiated with the Office of Technology Transfer
! at the California Institute of Technology.

! This software may be subject to U.S. export control laws. By accepting this
! software, the user agrees to comply with all applicable U.S. export laws and
! regulations. User has the responsibility to obtain export licenses, or other
! export authority as may be required before exporting such information to
! foreign countries or providing access to foreign persons.

module Parser_Tables_LR

  ! Parser tables for the LR parser generator.  The only reason for the
  ! existence of this module is so that LR doesn't need to generate a
  ! module, and be told its name.  This enables MLS L2 and LR to have
  ! different parsers, but use the same Parser module, simplifying the
  ! "make" process.

  ! The only reason the next four declarations are here instead of being
  ! generated by LR is so that we can put the RCS info here.

  use Symbol_Types
  use Tree_Types
  implicit NONE
  public

!---------------------------- RCS Module Info ------------------------------
  character (len=*), private, parameter :: ModuleName= &
       "$RCSfile$"
  private :: not_used_here 
!---------------------------------------------------------------------------

  include "Parser_LR.f9h"

!--------------------------- end bloc --------------------------------------
  logical function not_used_here()
  character (len=*), parameter :: IdParm = &
       "$Id$"
  character (len=len(idParm)) :: Id = idParm
    not_used_here = (id(1:1) == ModuleName(1:1))
    print *, Id ! .mod files sometimes change if PRINT is added
  end function not_used_here
!---------------------------------------------------------------------------

end module Parser_Tables_LR

! $Log$
