# $Id$

# Fortran compiler:
FC = f95

# Compiler options:
FOPTS = -g -C=all
#FOPTS = -O

# Path to source files:
S = ..

# Path to .mod files:
M = $(HOME)/mlspgs/lib/NAG

# Option to specify path to .mod files:
I = -I

# Beginning of path to libraries:
TOOLKIT = /software/SRC/TOOLKIT-5.2.6v1.00.NAG

# Beginning of path to HDFEOS libraries:
HDFEOS = /van1/opt/TOOLKIT
#HDFEOS = $(TOOLKIT)

# Path to Configuration parser
C = $(HOME)/mlspgs/lib/cf_parser/NAG

# Platform (used in a directory path in ../Makefile.inc):
PLATFORM = linux

# Path to libPGSTK
PGSTK = $(HOME)/mlspgs/SDPToolkit/NAG
#PGSTK = $(TOOLKIT)/lib/$(PLATFORM)

include $S/Makefile.inc

# $Log$
