#Makefile.dep -- a file to be included by a Makefile
#to compile a Fortran 9x program or library
OBJS = \
table_dumper.o    table_generator.o    test.o  \
 
# using f90makedep.pl to calculate dependencies 
table_dumper.o: table_dumper.f90 $(dir1)MLSCF.o $(dir1)declaration_table.o \
	$(dir1)intrinsic.o $(dir1)output_m.o $(dir1)string_table.o
table_generator.o: table_generator.f90 $(dir1)MLSCF.o \
	$(dir1)declaration_table.o $(dir1)expr_m.o $(dir1)intrinsic.o \
	$(dir1)lexer_core.o $(dir1)output_m.o $(dir1)string_table.o \
	$(dir1)toggles_core.o $(dir1)trace_m.o $(dir1)tree.o \
	$(dir1)tree_types.o
test.o: test.f90 $(dir1)MLSCF.o $(dir1)machine.o $(dir1)output_m.o \
	$(dir1)toggles_core.o $(dir2)getCF_m.o
 
#End of Makefile.dep
 
