#Makefile.dep -- a file to be included by a Makefile
#to compile a Fortran 9x program or library
OBJS = \
table_dumper.o    table_generator.o    test.o  \
 
# using f90makedep.pl to calculate dependencies 
table_dumper.o: table_dumper.f90
table_generator.o: table_generator.f90
test.o: test.f90
 
#End of Makefile.dep
 
